Ginkgo: gko::BatchLinOp Class Reference
gko::BatchLinOp Class Reference abstract
Public Member Functions
BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x)
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
const BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x) const
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
size_type get_num_batch_entries () const noexcept
Returns the number of batches in the batch operator.
void set_size (const batch_dim< 2 > &size)
Sets the size of the batch operator.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
virtual bool apply_uses_initial_guess () const
Returns true if the batch operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
BatchLinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Member Function Documentation
apply() [1/4]
BatchLinOp* gko::BatchLinOp::apply (const BatchLinOp * alpha, const BatchLinOp * b, const BatchLinOp * beta, BatchLinOp * x) inline
Performs the operation x = alpha * op(b) + beta * x.
Parameters
alpha scaling of the result of op(b)
b vector(s) on which the operator is applied
beta scaling of the input x
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply() [2/4]
const BatchLinOp* gko::BatchLinOp::apply (const BatchLinOp * alpha, const BatchLinOp * b, const BatchLinOp * beta, BatchLinOp * x) const inline
Parameters
alpha scaling of the result of op(b)
b vector(s) on which the operator is applied
beta scaling of the input x
x output vector(s)
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply() [3/4]
BatchLinOp* gko::BatchLinOp::apply (const BatchLinOp * b, BatchLinOp * x) inline
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
Performs the operation x = op(b), where op is this batch linear operator.
Parameters
b the input batch vector(s) on which the batch operator is applied
x the output batch vector(s) where the result is stored
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply() [4/4]
const BatchLinOp* gko::BatchLinOp::apply (const BatchLinOp * b, BatchLinOp * x) const inline
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
Performs the operation x = op(b), where op is this batch linear operator.
Parameters
b the input batch vector(s) on which the batch operator is applied
x the output batch vector(s) where the result is stored
Returns
this
References gko::PolymorphicObject::get_executor(), and gko::make_temporary_clone().
apply_uses_initial_guess()
virtual bool gko::BatchLinOp::apply_uses_initial_guess () const inline virtual
Returns true if the batch operator uses the data given in x as an initial guess.
Returns false otherwise.
Returns
true if the batch operator uses the data given in x as an initial guess. Returns false otherwise.
Reimplemented in gko::solver::BatchRichardson< ValueType >, gko::solver::BatchIdr< ValueType >, gko::solver::BatchCg< ValueType >, gko::solver::BatchBicgstab< ValueType >, gko::solver::BatchGmres< ValueType >, and gko::solver::BatchDirect< ValueType >.
get_num_batch_entries()
size_type gko::BatchLinOp::get_num_batch_entries () const inline noexcept
Returns the number of batches in the batch operator.
Returns
number of batches in the batch operator
References gko::batch_dim< Dimensionality, DimensionType >::get_num_batch_entries().
Referenced by gko::matrix::BatchDense< value_type >::at(), gko::matrix::BatchDense< value_type >::get_const_values(), gko::matrix::BatchDense< value_type >::get_num_stored_elements(), gko::matrix::BatchDense< value_type >::get_values(), gko::matrix::BatchCsr< ValueType, IndexType >::unbatch(), and gko::matrix::BatchDense< value_type >::unbatch().
get_size()
const batch_dim<2>& gko::BatchLinOp::get_size () const inline noexcept
Returns the size of the batch operator.
Returns
size of the batch operator
Referenced by gko::matrix::BatchCsr< ValueType, IndexType >::unbatch(), and gko::matrix::BatchDense< value_type >::unbatch().
set_size()
void gko::BatchLinOp::set_size (const batch_dim< 2 > & size) inline
Sets the size of the batch operator.
Parameters
size to be set
The documentation for this class was generated from the following file:
ginkgo/core/base/batch_lin_op.hpp