Ginkgo: gko::matrix::BatchDiagonal< ValueType > Class Template Reference
gko::matrix::BatchDiagonal< ValueType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | BatchLinOp
BatchDiagonal is a batch matrix format which explicitly stores all values of the matrix in each of the batches.
#include <ginkgo/core/matrix/batch_diagonal.hpp>
Public Types
using value_type = ValueType
using index_type = int32
using transposed_type = BatchDiagonal< ValueType >
using unbatch_type = Diagonal< ValueType >
using mat_data = gko::matrix_data< ValueType, int64 >
using mat_data32 = gko::matrix_data< ValueType, int32 >
using absolute_type = remove_complex< BatchDiagonal >
using complex_type = to_complex< BatchDiagonal >
Public Types inherited from gko::EnablePolymorphicAssignment< BatchDiagonal< ValueType > >
using result_type = BatchDiagonal< ValueType >
Public Types inherited from gko::ConvertibleTo< BatchDiagonal< ValueType > >
using result_type = BatchDiagonal< ValueType >
Public Types inherited from gko::ConvertibleTo< BatchDiagonal< next_precision< ValueType > > >
using result_type = BatchDiagonal< next_precision< ValueType > >
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Member Functions
void convert_to (BatchDiagonal< next_precision< ValueType >> *result) const override
void move_to (BatchDiagonal< next_precision< ValueType >> *result) override
void read (const std::vector< mat_data > &data) override
Read from a COO-type matrix data object into this batch diagonal matrix.
void read (const std::vector< mat_data32 > &data) override
Read from a COO-type matrix data object into this batch diagonal matrix.
void write (std::vector< mat_data > &data) const override
void write (std::vector< mat_data32 > &data) const override
std::unique_ptr< BatchLinOp > transpose () const override
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
std::unique_ptr< BatchLinOp > conj_transpose () const override
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
std::vector< std::unique_ptr< unbatch_type > > unbatch () const
Unbatches the batched dense and creates a std::vector of Diagonal matrices.
value_type * get_values () noexcept
Returns a pointer to the array of values of the matrix.
value_type * get_values (size_type batch) noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values () const noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values (size_type batch) const noexcept
Returns a pointer to the array of values of the matrix.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the batch matrix, cumulative across all the batches.
size_type get_num_stored_elements (size_type batch) const noexcept
Returns the number of elements explicitly stored at a specific batch index.
ValueType & at (size_type batch, size_type idx) noexcept
Returns a single element for a particular batch entry.
ValueType at (size_type batch, size_type idx) const noexcept
Returns a single element for a particular batch entry.
Public Member Functions inherited from gko::EnableBatchLinOp< BatchDiagonal< ValueType > >
const BatchDiagonal< ValueType > * apply (const BatchLinOp *b, BatchLinOp *x) const
BatchDiagonal< ValueType > * apply (const BatchLinOp *b, BatchLinOp *x)
const BatchDiagonal< ValueType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
BatchDiagonal< ValueType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchDiagonal< ValueType >, BatchLinOp >
std::unique_ptr< BatchDiagonal< ValueType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchDiagonal< ValueType > > create_default () const
std::unique_ptr< BatchDiagonal< ValueType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchDiagonal< ValueType > > clone () const
BatchDiagonal< ValueType > * copy_from (const PolymorphicObject *other)
BatchDiagonal< ValueType > * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchDiagonal< ValueType > * clear ()
Public Member Functions inherited from gko::BatchLinOp
BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x)
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
const BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x) const
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
size_type get_num_batch_entries () const noexcept
Returns the number of batches in the batch operator.
void set_size (const batch_dim< 2 > &size)
Sets the size of the batch operator.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
virtual bool apply_uses_initial_guess () const
Returns true if the batch operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
BatchLinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::EnablePolymorphicAssignment< BatchDiagonal< ValueType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchDiagonal< next_precision< ValueType > > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, int32 >
virtual void read (const std::vector< matrix_data< ValueType, int32 >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, int32 >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, int64 >
virtual void read (const std::vector< matrix_data< ValueType, int64 >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, int64 >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, int32 >
virtual void write (std::vector< matrix_data< ValueType, int32 >> &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, int64 >
virtual void write (std::vector< matrix_data< ValueType, int64 >> &data) const=0
Writes a matrix to a matrix_data structure.
Static Public Member Functions
static std::unique_ptr< BatchDiagonal > create_with_config_of (const BatchDiagonal *other)
Creates a BatchDiagonal matrix with the configuration of another BatchDiagonal matrix.
Static Public Member Functions inherited from gko::EnableCreateMethod< BatchDiagonal< ValueType > >
static std::unique_ptr< BatchDiagonal< ValueType > > create (Args &&... args)
Friends
class EnableCreateMethod< BatchDiagonal >
class EnablePolymorphicObject< BatchDiagonal, BatchLinOp >
class BatchDiagonal< to_complex< ValueType > >
class BatchDiagonal< next_precision< ValueType > >
Detailed Description
template<typename ValueType = default_precision>
class gko::matrix::BatchDiagonal< ValueType >
BatchDiagonal is a batch matrix format which explicitly stores all values of the matrix in each of the batches.
The values in each of the batches are stored in row-major format (values belonging to the same row appear consecutive in the memory). Optionally, rows can be padded for better memory access.
Template Parameters
ValueType precision of matrix elements
Note
While this format is not very useful for storing sparse matrices, it is often suitable to store vectors, and sets of vectors.
Member Function Documentation
at() [1/2]
template<typename ValueType = default_precision> ValueType gko::matrix::BatchDiagonal< ValueType >::at (size_type batch, size_type idx) const inline noexcept
Returns a single element for a particular batch entry.
Parameters
batch the batch index to be queried
idx a linear index of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the host results in a runtime error)
This method may not be the fastest way to access matrix entries.
See also
get_values, get_const_values
References gko::Array< ValueType >::get_const_data().
at() [2/2]
template<typename ValueType = default_precision> ValueType& gko::matrix::BatchDiagonal< ValueType >::at (size_type batch, size_type idx) inline noexcept
Returns a single element for a particular batch entry.
Parameters
batch the batch index to be queried
idx a linear index of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the host results in a runtime error)
This method may not be the fastest way to access matrix entries.
See also
get_values, get_const_values
References gko::Array< ValueType >::get_data().
Referenced by gko::matrix::BatchDiagonal< ValueType >::get_const_values(), gko::matrix::BatchDiagonal< ValueType >::get_num_stored_elements(), gko::matrix::BatchDiagonal< ValueType >::get_values(), and gko::matrix::BatchDiagonal< ValueType >::unbatch().
conj_transpose()
template<typename ValueType = default_precision> std::unique_ptr<BatchLinOp> gko::matrix::BatchDiagonal< ValueType >::conj_transpose () const override virtual
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::BatchTransposable.
create_with_config_of()
template<typename ValueType = default_precision> static std::unique_ptr<BatchDiagonal> gko::matrix::BatchDiagonal< ValueType >::create_with_config_of (const BatchDiagonal< ValueType > * other) inline static
Creates a BatchDiagonal matrix with the configuration of another BatchDiagonal matrix.
Parameters
other The other matrix whose configuration needs to copied.
get_const_values() [1/2]
template<typename ValueType = default_precision> const value_type* gko::matrix::BatchDiagonal< ValueType >::get_const_values () const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchDiagonal< ValueType >::unbatch().
get_const_values() [2/2]
template<typename ValueType = default_precision> const value_type* gko::matrix::BatchDiagonal< ValueType >::get_const_values (size_type batch) const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::matrix::BatchDiagonal< ValueType >::at(), gko::Array< ValueType >::get_const_data(), gko::BatchLinOp::get_num_batch_entries(), and gko::BatchLinOp::get_size().
get_num_stored_elements() [1/2]
template<typename ValueType = default_precision> size_type gko::matrix::BatchDiagonal< ValueType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the batch matrix, cumulative across all the batches.
Returns
the number of elements explicitly stored in the matrix, cumulative across all the batches
References gko::Array< ValueType >::get_num_elems().
get_num_stored_elements() [2/2]
template<typename ValueType = default_precision> size_type gko::matrix::BatchDiagonal< ValueType >::get_num_stored_elements (size_type batch) const inline noexcept
Returns the number of elements explicitly stored at a specific batch index.
Parameters
batch the batch index to be queried
Returns
the number of elements explicitly stored in the matrix
References gko::matrix::BatchDiagonal< ValueType >::at(), gko::Array< ValueType >::get_const_data(), gko::BatchLinOp::get_num_batch_entries(), and gko::BatchLinOp::get_size().
get_values() [1/2]
template<typename ValueType = default_precision> value_type* gko::matrix::BatchDiagonal< ValueType >::get_values () inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
References gko::Array< ValueType >::get_data().
get_values() [2/2]
template<typename ValueType = default_precision> value_type* gko::matrix::BatchDiagonal< ValueType >::get_values (size_type batch) inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
References gko::matrix::BatchDiagonal< ValueType >::at(), gko::Array< ValueType >::get_const_data(), gko::Array< ValueType >::get_data(), gko::BatchLinOp::get_num_batch_entries(), and gko::BatchLinOp::get_size().
read() [1/2]
template<typename ValueType = default_precision> void gko::matrix::BatchDiagonal< ValueType >::read (const std::vector< mat_data > & data) override
Read from a COO-type matrix data object into this batch diagonal matrix.
Any off-diagonal entries in the input are ignored.
read() [2/2]
template<typename ValueType = default_precision> void gko::matrix::BatchDiagonal< ValueType >::read (const std::vector< mat_data32 > & data) override
Read from a COO-type matrix data object into this batch diagonal matrix.
Any off-diagonal entries in the input are ignored.
transpose()
template<typename ValueType = default_precision> std::unique_ptr<BatchLinOp> gko::matrix::BatchDiagonal< ValueType >::transpose () const override virtual
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new transposed object
Implements gko::BatchTransposable.
unbatch()
template<typename ValueType = default_precision> std::vector<std::unique_ptr<unbatch_type> > gko::matrix::BatchDiagonal< ValueType >::unbatch () const inline
Unbatches the batched dense and creates a std::vector of Diagonal matrices.
Returns
a std::vector containing the Diagonal matrices.
References gko::matrix::BatchDiagonal< ValueType >::at(), gko::Array< ValueType >::get_const_data(), gko::matrix::BatchDiagonal< ValueType >::get_const_values(), gko::PolymorphicObject::get_executor(), gko::BatchLinOp::get_num_batch_entries(), and gko::BatchLinOp::get_size().
The documentation for this class was generated from the following files:
ginkgo/core/matrix/batch_dense.hpp
ginkgo/core/matrix/batch_diagonal.hpp