Ginkgo: gko::matrix::BatchCsr< ValueType, IndexType > Class Template Reference
gko::matrix::BatchCsr< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | BatchLinOp
BatchCsr is a matrix format which stores only the nonzero coefficients by compressing each row of the matrix (compressed sparse row format).
#include <ginkgo/core/matrix/batch_csr.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using transposed_type = BatchCsr< ValueType, IndexType >
using unbatch_type = Csr< ValueType, IndexType >
using mat_data = matrix_data< ValueType, IndexType >
using absolute_type = remove_complex< BatchCsr >
Public Types inherited from gko::EnablePolymorphicAssignment< BatchCsr< ValueType, IndexType > >
using result_type = BatchCsr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchCsr< ValueType, IndexType > >
using result_type = BatchCsr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchCsr< next_precision< ValueType >, IndexType > >
using result_type = BatchCsr< next_precision< ValueType >, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchDense< ValueType > >
using result_type = BatchDense< ValueType >
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Member Functions
void convert_to (BatchCsr< ValueType, IndexType > *result) const override
void move_to (BatchCsr< ValueType, IndexType > *result) override
void convert_to (BatchCsr< next_precision< ValueType >, IndexType > *result) const override
void move_to (BatchCsr< next_precision< ValueType >, IndexType > *result) override
void convert_to (BatchDense< ValueType > *result) const override
void move_to (BatchDense< ValueType > *result) override
void read (const std::vector< mat_data > &data) override
void write (std::vector< mat_data > &data) const override
std::unique_ptr< BatchLinOp > transpose () const override
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
std::unique_ptr< BatchLinOp > conj_transpose () const override
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
std::vector< std::unique_ptr< unbatch_type > > unbatch () const
Unbatches the BatchCsr matrix into distinct matrices of Csr type.
void sort_by_column_index ()
Sorts all (value, col_idx) pairs in each row by column index.
bool is_sorted_by_column_index () const
Tests if all row entry pairs (value, col_idx) are sorted by column index.
value_type * get_values () noexcept
Returns the values of the matrix.
const value_type * get_const_values () const noexcept
Returns the values of the matrix.
index_type * get_col_idxs () noexcept
Returns the column indexes of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indexes of the matrix.
index_type * get_row_ptrs () noexcept
Returns the row pointers of the matrix.
const index_type * get_const_row_ptrs () const noexcept
Returns the row pointers of the matrix.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
Public Member Functions inherited from gko::EnableBatchLinOp< BatchCsr< ValueType, IndexType > >
const BatchCsr< ValueType, IndexType > * apply (const BatchLinOp *b, BatchLinOp *x) const
BatchCsr< ValueType, IndexType > * apply (const BatchLinOp *b, BatchLinOp *x)
const BatchCsr< ValueType, IndexType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
BatchCsr< ValueType, IndexType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchCsr< ValueType, IndexType >, BatchLinOp >
std::unique_ptr< BatchCsr< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchCsr< ValueType, IndexType > > create_default () const
std::unique_ptr< BatchCsr< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchCsr< ValueType, IndexType > > clone () const
BatchCsr< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
BatchCsr< ValueType, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchCsr< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::BatchLinOp
BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x)
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
const BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x) const
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
size_type get_num_batch_entries () const noexcept
Returns the number of batches in the batch operator.
void set_size (const batch_dim< 2 > &size)
Sets the size of the batch operator.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
virtual bool apply_uses_initial_guess () const
Returns true if the batch operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
BatchLinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::EnablePolymorphicAssignment< BatchCsr< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchCsr< next_precision< ValueType >, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchDense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, IndexType >
virtual void read (const std::vector< matrix_data< ValueType, IndexType >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, IndexType >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, IndexType >
virtual void write (std::vector< matrix_data< ValueType, IndexType >> &data) const =0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::EnableBatchScaling< ValueType >
void batch_scale (const BatchLinOp *const left_scale, const BatchLinOp *const right_scale) override
Scales each matrix in a batch from the left and right.
Friends
class EnableCreateMethod< BatchCsr >
class EnablePolymorphicObject< BatchCsr, BatchLinOp >
class BatchCsr< to_complex< ValueType >, IndexType >
class BatchCsr< next_precision< ValueType >, IndexType >
Additional Inherited Members
Static Public Member Functions inherited from gko::EnableCreateMethod< BatchCsr< ValueType, IndexType > >
static std::unique_ptr< BatchCsr< ValueType, IndexType > > create (Args &&... args)
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::BatchCsr< ValueType, IndexType >
BatchCsr is a matrix format which stores only the nonzero coefficients by compressing each row of the matrix (compressed sparse row format).
Each of the individual batches are stored in a CSR matrix.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes
Note
Currently, BatchCsr can store matrices with batch entries that have the same sparsity pattern, but different values.
Member Function Documentation
conj_transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<BatchLinOp> gko::matrix::BatchCsr< ValueType, IndexType >::conj_transpose () const override virtual
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::BatchTransposable.
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
References gko::Array< ValueType >::get_data().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchCsr< ValueType, IndexType >::unbatch().
get_const_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_const_row_ptrs () const inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchCsr< ValueType, IndexType >::unbatch().
get_const_values()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_const_values () const inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchCsr< ValueType, IndexType >::unbatch().
get_num_stored_elements()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::BatchCsr< ValueType, IndexType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
Returns
the number of elements explicitly stored in the matrix, cumulative over all the batches
References gko::Array< ValueType >::get_num_elems().
Referenced by gko::matrix::BatchCsr< ValueType, IndexType >::unbatch().
get_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_row_ptrs () inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
References gko::Array< ValueType >::get_data().
get_values()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::BatchCsr< ValueType, IndexType >::get_values () inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
References gko::Array< ValueType >::get_data().
is_sorted_by_column_index()
template<typename ValueType = default_precision, typename IndexType = int32> bool gko::matrix::BatchCsr< ValueType, IndexType >::is_sorted_by_column_index () const
Tests if all row entry pairs (value, col_idx) are sorted by column index.
Returns
True if all row entry pairs (value, col_idx) are sorted by column index
transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<BatchLinOp> gko::matrix::BatchCsr< ValueType, IndexType >::transpose () const override virtual
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new transposed object
Implements gko::BatchTransposable.
unbatch()
template<typename ValueType = default_precision, typename IndexType = int32> std::vector<std::unique_ptr<unbatch_type> > gko::matrix::BatchCsr< ValueType, IndexType >::unbatch () const inline
Unbatches the BatchCsr matrix into distinct matrices of Csr type.
Returns
a std::vector containing the distinct Csr matrices.
References gko::batch_dim< Dimensionality, DimensionType >::at(), gko::matrix::BatchCsr< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::BatchCsr< ValueType, IndexType >::get_const_row_ptrs(), gko::matrix::BatchCsr< ValueType, IndexType >::get_const_values(), gko::PolymorphicObject::get_executor(), gko::BatchLinOp::get_num_batch_entries(), gko::matrix::BatchCsr< ValueType, IndexType >::get_num_stored_elements(), and gko::BatchLinOp::get_size().
The documentation for this class was generated from the following file:
ginkgo/core/matrix/batch_csr.hpp