Ginkgo: gko::matrix::BatchEll< ValueType, IndexType > Class Template Reference
gko::matrix::BatchEll< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | BatchLinOp
BatchEll is a matrix format which stores only the nonzero coefficients by compressing each row of the matrix (compressed sparse row format).
#include <ginkgo/core/matrix/batch_ell.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using transposed_type = BatchEll< ValueType, IndexType >
using unbatch_type = Ell< ValueType, IndexType >
using mat_data = matrix_data< ValueType, IndexType >
using absolute_type = remove_complex< BatchEll >
Public Types inherited from gko::EnablePolymorphicAssignment< BatchEll< ValueType, IndexType > >
using result_type = BatchEll< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchEll< ValueType, IndexType > >
using result_type = BatchEll< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchEll< next_precision< ValueType >, IndexType > >
using result_type = BatchEll< next_precision< ValueType >, IndexType >
Public Types inherited from gko::ConvertibleTo< BatchDense< ValueType > >
using result_type = BatchDense< ValueType >
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Member Functions
void convert_to (BatchEll< ValueType, IndexType > *result) const override
void move_to (BatchEll< ValueType, IndexType > *result) override
void convert_to (BatchEll< next_precision< ValueType >, IndexType > *result) const override
void move_to (BatchEll< next_precision< ValueType >, IndexType > *result) override
void convert_to (BatchDense< ValueType > *result) const override
void move_to (BatchDense< ValueType > *result) override
void read (const std::vector< mat_data > &data) override
void write (std::vector< mat_data > &data) const override
std::unique_ptr< BatchLinOp > transpose () const override
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
std::unique_ptr< BatchLinOp > conj_transpose () const override
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
std::vector< std::unique_ptr< unbatch_type > > unbatch () const
Unbatches the BatchEll matrix into distinct matrices of Ell type.
value_type * get_values () noexcept
Returns the values of the matrix.
const value_type * get_const_values () const noexcept
Returns the values of the matrix.
index_type * get_col_idxs () noexcept
Returns the column indexes of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indexes of the matrix.
const batch_num_stored_elems_per_row & get_num_stored_elements_per_row () const noexcept
Returns the number of stored elements per row.
const batch_stride & get_stride () const noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
value_type & val_at (size_type id, size_type row, size_type idx) noexcept
Returns the idx-th non-zero element of the row-th row .
value_type val_at (size_type id, size_type row, size_type idx) const noexcept
Returns the idx-th non-zero element of the row-th row .
index_type & col_at (size_type row, size_type idx) noexcept
Returns the idx-th column index of the row-th row .
index_type col_at (size_type row, size_type idx) const noexcept
Returns the idx-th column index of the row-th row .
Public Member Functions inherited from gko::EnableBatchLinOp< BatchEll< ValueType, IndexType > >
const BatchEll< ValueType, IndexType > * apply (const BatchLinOp *b, BatchLinOp *x) const
BatchEll< ValueType, IndexType > * apply (const BatchLinOp *b, BatchLinOp *x)
const BatchEll< ValueType, IndexType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
BatchEll< ValueType, IndexType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchEll< ValueType, IndexType >, BatchLinOp >
std::unique_ptr< BatchEll< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchEll< ValueType, IndexType > > create_default () const
std::unique_ptr< BatchEll< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchEll< ValueType, IndexType > > clone () const
BatchEll< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
BatchEll< ValueType, IndexType > * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchEll< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::BatchLinOp
BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x)
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
const BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x) const
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
size_type get_num_batch_entries () const noexcept
Returns the number of batches in the batch operator.
void set_size (const batch_dim< 2 > &size)
Sets the size of the batch operator.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
virtual bool apply_uses_initial_guess () const
Returns true if the batch operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
BatchLinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::EnablePolymorphicAssignment< BatchEll< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchEll< next_precision< ValueType >, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchDense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, IndexType >
virtual void read (const std::vector< matrix_data< ValueType, IndexType >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, IndexType >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, IndexType >
virtual void write (std::vector< matrix_data< ValueType, IndexType >> &data) const =0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::BatchScaledIdentityAddable
virtual void add_scaled_identity (const BatchLinOp *a, const BatchLinOp *b)
Scales this and adds another scalar times the identity to it.
Static Public Member Functions
static std::unique_ptr< BatchEll > create_from_batch_csc (std::shared_ptr< const Executor > exec, const size_type num_batch_entries, const dim< 2 > &size, const size_type num_elems_per_row, const gko::Array< ValueType > &values, const gko::Array< IndexType > &row_idxs, const gko::Array< IndexType > &col_ptrs)
static std::unique_ptr< const BatchEll > create_const (std::shared_ptr< const Executor > exec, const batch_dim< 2 > &size, const batch_stride &num_stored_elems_per_row, const batch_stride &stride, gko::detail::ConstArrayView< ValueType > &&values, gko::detail::ConstArrayView< IndexType > &&col_idxs)
Creates an immutable BatchEll matrix from a set of constant arrays.
Static Public Member Functions inherited from gko::EnableCreateMethod< BatchEll< ValueType, IndexType > >
static std::unique_ptr< BatchEll< ValueType, IndexType > > create (Args &&... args)
Friends
class EnableCreateMethod< BatchEll >
class EnablePolymorphicObject< BatchEll, BatchLinOp >
class BatchEll< to_complex< ValueType >, IndexType >
class BatchEll< next_precision< ValueType >, IndexType >
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::BatchEll< ValueType, IndexType >
BatchEll is a matrix format which stores only the nonzero coefficients by compressing each row of the matrix (compressed sparse row format).
Each of the individual batches are stored in a CSR matrix.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes
Note
Currently, BatchEll can store matrices with batch entries that have the same sparsity pattern, but different values.
Member Function Documentation
col_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type gko::matrix::BatchEll< ValueType, IndexType >::col_at (size_type row, size_type idx) const inline noexcept
Returns the idx-th column index of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::matrix::BatchEll< ValueType, IndexType >::get_const_col_idxs().
col_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type& gko::matrix::BatchEll< ValueType, IndexType >::col_at (size_type row, size_type idx) inline noexcept
Returns the idx-th column index of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::matrix::BatchEll< ValueType, IndexType >::get_col_idxs().
conj_transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<BatchLinOp> gko::matrix::BatchEll< ValueType, IndexType >::conj_transpose () const override virtual
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::BatchTransposable.
create_const()
template<typename ValueType = default_precision, typename IndexType = int32> static std::unique_ptr<const BatchEll> gko::matrix::BatchEll< ValueType, IndexType >::create_const (std::shared_ptr< const Executor > exec, const batch_dim< 2 > & size, const batch_stride & num_stored_elems_per_row, const batch_stride & stride, gko::detail::ConstArrayView< ValueType > && values, gko::detail::ConstArrayView< IndexType > && col_idxs) inline static
Creates an immutable BatchEll matrix from a set of constant arrays.
Parameters
exec the executor to create the matrix on
size the dimensions of the matrix
values the value array of the matrix
col_idxs the column index array of the matrix
num_stored_elems_per_row the number of stored nonzeros per row
stride the column-stride of the value and column index array
Returns
A smart pointer to the constant matrix wrapping the input arrays (if they reside on the same executor as the matrix) or a copy of the arrays on the correct executor.
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::BatchEll< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
References gko::Array< ValueType >::get_data().
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::col_at().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::BatchEll< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::col_at(), and gko::matrix::BatchEll< ValueType, IndexType >::unbatch().
get_const_values()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::BatchEll< ValueType, IndexType >::get_const_values () const inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::Array< ValueType >::get_const_data().
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::unbatch().
get_num_stored_elements()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::BatchEll< ValueType, IndexType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
Returns
the number of elements explicitly stored in the matrix, cumulative over all the batches
References gko::Array< ValueType >::get_num_elems().
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::unbatch().
get_num_stored_elements_per_row()
template<typename ValueType = default_precision, typename IndexType = int32> const batch_num_stored_elems_per_row& gko::matrix::BatchEll< ValueType, IndexType >::get_num_stored_elements_per_row () const inline noexcept
Returns the number of stored elements per row.
Returns
the number of stored elements per row.
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::unbatch().
get_stride()
template<typename ValueType = default_precision, typename IndexType = int32> const batch_stride& gko::matrix::BatchEll< ValueType, IndexType >::get_stride () const inline noexcept
Returns the number of elements explicitly stored in the matrix, cumulative over all the batches.
Returns
the number of elements explicitly stored in the matrix, cumulative over all the batches
Referenced by gko::matrix::BatchEll< ValueType, IndexType >::unbatch().
get_values()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::BatchEll< ValueType, IndexType >::get_values () inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
References gko::Array< ValueType >::get_data().
transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<BatchLinOp> gko::matrix::BatchEll< ValueType, IndexType >::transpose () const override virtual
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new transposed object
Implements gko::BatchTransposable.
unbatch()
template<typename ValueType = default_precision, typename IndexType = int32> std::vector<std::unique_ptr<unbatch_type> > gko::matrix::BatchEll< ValueType, IndexType >::unbatch () const inline
Unbatches the BatchEll matrix into distinct matrices of Ell type.
Returns
a std::vector containing the distinct Ell matrices.
References gko::matrix::BatchEll< ValueType, IndexType >::get_const_col_idxs(), gko::matrix::BatchEll< ValueType, IndexType >::get_const_values(), gko::PolymorphicObject::get_executor(), gko::BatchLinOp::get_num_batch_entries(), gko::matrix::BatchEll< ValueType, IndexType >::get_num_stored_elements(), gko::matrix::BatchEll< ValueType, IndexType >::get_num_stored_elements_per_row(), gko::BatchLinOp::get_size(), and gko::matrix::BatchEll< ValueType, IndexType >::get_stride().
val_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type gko::matrix::BatchEll< ValueType, IndexType >::val_at (size_type id, size_type row, size_type idx) const inline noexcept
Returns the idx-th non-zero element of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::Array< ValueType >::get_const_data().
val_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type& gko::matrix::BatchEll< ValueType, IndexType >::val_at (size_type id, size_type row, size_type idx) inline noexcept
Returns the idx-th non-zero element of the row-th row .
Parameters
row the row of the requested element
idx the idx-th stored element of the row
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::Array< ValueType >::get_data().
The documentation for this class was generated from the following file:
ginkgo/core/matrix/batch_ell.hpp