Ginkgo: gko::matrix::BatchDense< ValueType > Class Template Reference
gko::matrix::BatchDense< ValueType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | BatchLinOp
BatchDense is a batch matrix format which explicitly stores all values of the matrix in each of the batches.
#include <ginkgo/core/matrix/batch_dense.hpp>
Public Types
using value_type = ValueType
using index_type = int32
using transposed_type = BatchDense< ValueType >
using unbatch_type = Dense< ValueType >
using mat_data = gko::matrix_data< ValueType, int64 >
using mat_data32 = gko::matrix_data< ValueType, int32 >
using absolute_type = remove_complex< BatchDense >
using complex_type = to_complex< BatchDense >
using row_major_range = gko::range< gko::accessor::row_major< ValueType, 2 > >
Public Types inherited from gko::EnablePolymorphicAssignment< BatchDense< ValueType > >
using result_type = BatchDense< ValueType >
Public Types inherited from gko::ConvertibleTo< BatchDense< ValueType > >
using result_type = BatchDense< ValueType >
Public Types inherited from gko::ConvertibleTo< BatchDense< next_precision< ValueType > > >
using result_type = BatchDense< next_precision< ValueType > >
Public Types inherited from gko::ConvertibleTo< BatchCsr< ValueType, int32 > >
using result_type = BatchCsr< ValueType, int32 >
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::BatchReadableFromMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::BatchWritableToMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Member Functions
void convert_to (BatchDense< next_precision< ValueType >> *result) const override
void move_to (BatchDense< next_precision< ValueType >> *result) override
void convert_to (BatchCsr< ValueType, index_type > *result) const override
void move_to (BatchCsr< ValueType, index_type > *result) override
void read (const std::vector< mat_data > &data) override
void read (const std::vector< mat_data32 > &data) override
void write (std::vector< mat_data > &data) const override
void write (std::vector< mat_data32 > &data) const override
std::unique_ptr< BatchLinOp > transpose () const override
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
std::unique_ptr< BatchLinOp > conj_transpose () const override
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
std::vector< std::unique_ptr< unbatch_type > > unbatch () const
Unbatches the batched dense and creates a std::vector of Dense matrices.
value_type * get_values () noexcept
Returns a pointer to the array of values of the matrix.
value_type * get_values (size_type batch) noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values () const noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values (size_type batch) const noexcept
Returns a pointer to the array of values of the matrix.
const batch_stride & get_stride () const noexcept
Returns the batch_stride of the matrix.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the batch matrix, cumulative across all the batches.
size_type get_num_stored_elements (size_type batch) const noexcept
Returns the number of elements explicitly stored at a specific batch index.
value_type & at (size_type batch, size_type row, size_type col) noexcept
Returns a single element for a particular batch.
value_type at (size_type batch, size_type row, size_type col) const noexcept
Returns a single element for a particular batch.
ValueType & at (size_type batch, size_type idx) noexcept
Returns a single element for a particular batch entry.
ValueType at (size_type batch, size_type idx) const noexcept
Returns a single element for a particular batch.
void scale (const BatchLinOp *alpha)
Scales the matrix with a scalar (aka: BLAS scal).
void add_scaled (const BatchLinOp *alpha, const BatchLinOp *b)
Adds b scaled by alpha to the matrix (aka: BLAS axpy).
void compute_dot (const BatchLinOp *b, BatchLinOp *result) const
Computes the column-wise dot product of each matrix in this batch and its corresponding entry in b.
void compute_norm2 (BatchLinOp *result) const
Computes the Euclidean (L^2) norm of each matrix in this batch.
Public Member Functions inherited from gko::EnableBatchLinOp< BatchDense< ValueType > >
const BatchDense< ValueType > * apply (const BatchLinOp *b, BatchLinOp *x) const
BatchDense< ValueType > * apply (const BatchLinOp *b, BatchLinOp *x)
const BatchDense< ValueType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
BatchDense< ValueType > * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchDense< ValueType >, BatchLinOp >
std::unique_ptr< BatchDense< ValueType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchDense< ValueType > > create_default () const
std::unique_ptr< BatchDense< ValueType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchDense< ValueType > > clone () const
BatchDense< ValueType > * copy_from (const PolymorphicObject *other)
BatchDense< ValueType > * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchDense< ValueType > * clear ()
Public Member Functions inherited from gko::BatchLinOp
BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x)
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
const BatchLinOp * apply (const BatchLinOp *b, BatchLinOp *x) const
Applies a batch linear operator to a batch vector (or a sequence of batch of vectors).
BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const BatchLinOp * apply (const BatchLinOp *alpha, const BatchLinOp *b, const BatchLinOp *beta, BatchLinOp *x) const
size_type get_num_batch_entries () const noexcept
Returns the number of batches in the batch operator.
void set_size (const batch_dim< 2 > &size)
Sets the size of the batch operator.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
virtual bool apply_uses_initial_guess () const
Returns true if the batch operator uses the data given in x as an initial guess.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
BatchLinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::EnablePolymorphicAssignment< BatchDense< ValueType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchDense< next_precision< ValueType > > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< BatchCsr< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, int32 >
virtual void read (const std::vector< matrix_data< ValueType, int32 >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, int32 >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchReadableFromMatrixData< ValueType, int64 >
virtual void read (const std::vector< matrix_data< ValueType, int64 >> &data)=0
Reads a batch matrix from a std::vector of matrix_data objects.
void read (const std::vector< matrix_assembly_data< ValueType, int64 >> &assembly_data)
Reads a matrix from a std::vector of matrix_assembly_data objects.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, int32 >
virtual void write (std::vector< matrix_data< ValueType, int32 >> &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::BatchWritableToMatrixData< ValueType, int64 >
virtual void write (std::vector< matrix_data< ValueType, int64 >> &data) const=0
Writes a matrix to a matrix_data structure.
Static Public Member Functions
static std::unique_ptr< BatchDense > create_with_config_of (const BatchDense *other)
Creates a BatchDense matrix with the configuration of another BatchDense matrix.
Static Public Member Functions inherited from gko::EnableCreateMethod< BatchDense< ValueType > >
static std::unique_ptr< BatchDense< ValueType > > create (Args &&... args)
Friends
class EnableCreateMethod< BatchDense >
class EnablePolymorphicObject< BatchDense, BatchLinOp >
class BatchDense< to_complex< ValueType > >
class BatchCsr< ValueType, int32 >
class BatchDense< next_precision< ValueType > >
Detailed Description
template<typename ValueType = default_precision>
class gko::matrix::BatchDense< ValueType >
BatchDense is a batch matrix format which explicitly stores all values of the matrix in each of the batches.
The values in each of the batches are stored in row-major format (values belonging to the same row appear consecutive in the memory). Optionally, rows can be padded for better memory access.
Template Parameters
ValueType precision of matrix elements
Note
While this format is not very useful for storing sparse matrices, it is often suitable to store vectors, and sets of vectors.
Member Function Documentation
add_scaled()
template<typename ValueType = default_precision> void gko::matrix::BatchDense< ValueType >::add_scaled (const BatchLinOp * alpha, const BatchLinOp * b) inline
Adds b scaled by alpha to the matrix (aka: BLAS axpy).
Parameters
alpha If alpha is 1x1 BatchDense matrix, the entire matrix is scaled by alpha. If it is a BatchDense row vector of values, then i-th column of the matrix is scaled with the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
b a matrix of the same dimension as this
at() [1/4]
template<typename ValueType = default_precision> ValueType gko::matrix::BatchDense< ValueType >::at (size_type batch, size_type idx) const inline noexcept
Returns a single element for a particular batch.
Parameters
batch the batch index to be queried
row the row of the requested element
col the column of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
at() [2/4]
template<typename ValueType = default_precision> ValueType& gko::matrix::BatchDense< ValueType >::at (size_type batch, size_type idx) inline noexcept
Returns a single element for a particular batch entry.
Useful for iterating across all elements of the matrix. However, it is less efficient than the two-parameter variant of this method.
Parameters
batch the batch index to be queried
idx a linear index of the requested element (ignoring the stride)
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
at() [3/4]
template<typename ValueType = default_precision> value_type gko::matrix::BatchDense< ValueType >::at (size_type batch, size_type row, size_type col) const inline noexcept
Returns a single element for a particular batch.
Parameters
batch the batch index to be queried
row the row of the requested element
col the column of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
at() [4/4]
template<typename ValueType = default_precision> value_type& gko::matrix::BatchDense< ValueType >::at (size_type batch, size_type row, size_type col) inline noexcept
Returns a single element for a particular batch.
Parameters
batch the batch index to be queried
row the row of the requested element
col the column of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
Referenced by gko::matrix::BatchDense< value_type >::unbatch().
compute_dot()
template<typename ValueType = default_precision> void gko::matrix::BatchDense< ValueType >::compute_dot (const BatchLinOp * b, BatchLinOp * result) const inline
Computes the column-wise dot product of each matrix in this batch and its corresponding entry in b.
If the matrix has complex value_type, then the conjugate of this is taken.
Parameters
b a BatchDense matrix of same dimension as this
result a BatchDense row vector, used to store the dot product (the number of column in the vector must match the number of columns of this)
compute_norm2()
template<typename ValueType = default_precision> void gko::matrix::BatchDense< ValueType >::compute_norm2 (BatchLinOp * result) const inline
Computes the Euclidean (L^2) norm of each matrix in this batch.
Parameters
result a BatchDense row vector, used to store the norm (the number of columns in the vector must match the number of columns of this)
conj_transpose()
template<typename ValueType = default_precision> std::unique_ptr<BatchLinOp> gko::matrix::BatchDense< ValueType >::conj_transpose () const override virtual
Returns a BatchLinOp containing the conjugate transpose of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::BatchTransposable.
create_with_config_of()
template<typename ValueType = default_precision> static std::unique_ptr<BatchDense> gko::matrix::BatchDense< ValueType >::create_with_config_of (const BatchDense< ValueType > * other) inline static
Creates a BatchDense matrix with the configuration of another BatchDense matrix.
Parameters
other The other matrix whose configuration needs to copied.
get_const_values() [1/2]
template<typename ValueType = default_precision> const value_type* gko::matrix::BatchDense< ValueType >::get_const_values () const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
Referenced by gko::matrix::BatchDense< value_type >::unbatch().
get_const_values() [2/2]
template<typename ValueType = default_precision> const value_type* gko::matrix::BatchDense< ValueType >::get_const_values (size_type batch) const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
get_num_stored_elements() [1/2]
template<typename ValueType = default_precision> size_type gko::matrix::BatchDense< ValueType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the batch matrix, cumulative across all the batches.
Returns
the number of elements explicitly stored in the matrix, cumulative across all the batches
get_num_stored_elements() [2/2]
template<typename ValueType = default_precision> size_type gko::matrix::BatchDense< ValueType >::get_num_stored_elements (size_type batch) const inline noexcept
Returns the number of elements explicitly stored at a specific batch index.
Parameters
batch the batch index to be queried
Returns
the number of elements explicitly stored in the matrix
get_stride()
template<typename ValueType = default_precision> const batch_stride& gko::matrix::BatchDense< ValueType >::get_stride () const inline noexcept
Returns the batch_stride of the matrix.
Returns
the batch_stride of the matrix.
Referenced by gko::matrix::BatchDense< value_type >::unbatch().
get_values() [1/2]
template<typename ValueType = default_precision> value_type* gko::matrix::BatchDense< ValueType >::get_values () inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
get_values() [2/2]
template<typename ValueType = default_precision> value_type* gko::matrix::BatchDense< ValueType >::get_values (size_type batch) inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
scale()
template<typename ValueType = default_precision> void gko::matrix::BatchDense< ValueType >::scale (const BatchLinOp * alpha) inline
Scales the matrix with a scalar (aka: BLAS scal).
Parameters
alpha If alpha is 1x1 BatchDense matrix, the entire matrix (all batches) is scaled by alpha. If it is a BatchDense row vector of values, then i-th column of the matrix is scaled with the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
transpose()
template<typename ValueType = default_precision> std::unique_ptr<BatchLinOp> gko::matrix::BatchDense< ValueType >::transpose () const override virtual
Returns a BatchLinOp containing the transposes of the distinct entries of the BatchTransposable object.
Returns
a pointer to the new transposed object
Implements gko::BatchTransposable.
unbatch()
template<typename ValueType = default_precision> std::vector<std::unique_ptr<unbatch_type> > gko::matrix::BatchDense< ValueType >::unbatch () const inline
Unbatches the batched dense and creates a std::vector of Dense matrices.
Returns
a std::vector containing the Dense matrices.
The documentation for this class was generated from the following files:
ginkgo/core/base/batch_lin_op.hpp
ginkgo/core/matrix/batch_dense.hpp