Ginkgo: gko::batch_dim< Dimensionality, DimensionType > Struct Template Reference
gko::batch_dim< Dimensionality, DimensionType > Struct Template Reference
A type representing the dimensions of a multidimensional batch object.
#include <ginkgo/core/base/dim.hpp>
Public Types
using dimension_type = DimensionType
Public Member Functions
bool stores_equal_sizes () const
Checks if the batch_dim object stores equal sizes.
size_type get_num_batch_entries () const
Get the number of batch entries stored.
std::vector< dim< dimensionality, dimension_type > > get_batch_sizes () const
Get the sizes of all entries as a std::vector.
const dim< dimensionality, dimension_type > & at (const size_type batch_entry=0) const
Get the batch size at a particular index.
batch_dim (const size_type num_batch_entries=0, const dim< dimensionality, dimension_type > &common_size=dim< dimensionality, dimension_type >{})
Creates a batch_dim object which stores a uniform size for all batch entries.
batch_dim (const std::vector< dim< dimensionality, dimension_type >> &batch_sizes)
Creates a batch_dim object which stores possibly non-uniform sizes for the different batch entries.
Static Public Attributes
static constexpr size_type dimensionality = Dimensionality
Friends
bool operator== (const batch_dim &x, const batch_dim &y)
Checks if two batch_dim objects are equal.
Detailed Description
template<size_type Dimensionality = 2, typename DimensionType = size_type>
struct gko::batch_dim< Dimensionality, DimensionType >
A type representing the dimensions of a multidimensional batch object.
Template Parameters
Dimensionality number of dimensions of the object
DimensionType datatype used to represent each dimension
Constructor & Destructor Documentation
batch_dim() [1/2]
template<size_type Dimensionality = 2, typename DimensionType = size_type> gko::batch_dim< Dimensionality, DimensionType >::batch_dim (const size_type num_batch_entries = 0, const dim< dimensionality, dimension_type > & common_size = dim<dimensionality, dimension_type>{}) inline explicit
Creates a batch_dim object which stores a uniform size for all batch entries.
Parameters
num_batch_entries number of batch entries to be stored
common_size the common size of all the batch entries stored
Note
Use this constructor when uniform batches need to be stored.
batch_dim() [2/2]
template<size_type Dimensionality = 2, typename DimensionType = size_type> gko::batch_dim< Dimensionality, DimensionType >::batch_dim (const std::vector< dim< dimensionality, dimension_type >> & batch_sizes) inline
Creates a batch_dim object which stores possibly non-uniform sizes for the different batch entries.
Parameters
batch_sizes the std::vector object that stores the batch_sizes
Note
Use this constructor when non-uniform batches need to be stored.
Member Function Documentation
at()
template<size_type Dimensionality = 2, typename DimensionType = size_type> const dim<dimensionality, dimension_type>& gko::batch_dim< Dimensionality, DimensionType >::at (const size_type batch_entry = 0) const inline
Get the batch size at a particular index.
Parameters
batch_entry the index of the entry whose size is needed
Returns
the size of the batch entry at the requested batch-index
Referenced by gko::transpose(), and gko::matrix::BatchCsr< ValueType, IndexType >::unbatch().
get_batch_sizes()
template<size_type Dimensionality = 2, typename DimensionType = size_type> std::vector<dim<dimensionality, dimension_type> > gko::batch_dim< Dimensionality, DimensionType >::get_batch_sizes () const inline
Get the sizes of all entries as a std::vector.
Returns
the std::vector of batch sizes
get_num_batch_entries()
template<size_type Dimensionality = 2, typename DimensionType = size_type> size_type gko::batch_dim< Dimensionality, DimensionType >::get_num_batch_entries () const inline
Get the number of batch entries stored.
Returns
num_batch_entries
Referenced by gko::BatchLinOp::get_num_batch_entries(), and gko::transpose().
stores_equal_sizes()
template<size_type Dimensionality = 2, typename DimensionType = size_type> bool gko::batch_dim< Dimensionality, DimensionType >::stores_equal_sizes () const inline
Checks if the batch_dim object stores equal sizes.
Returns
bool representing whether equal sizes are being stored
Referenced by gko::transpose().
Friends And Related Function Documentation
operator==
template<size_type Dimensionality = 2, typename DimensionType = size_type> bool operator== (const batch_dim< Dimensionality, DimensionType > & x, const batch_dim< Dimensionality, DimensionType > & y) friend
Checks if two batch_dim objects are equal.
Parameters
x first object
y second object
Returns
true if and only if all dimensions of both objects are equal.
The documentation for this struct was generated from the following file:
ginkgo/core/base/dim.hpp