Ginkgo: gko::batch::BatchLinOp Class Reference
gko::batch::BatchLinOp Class Reference
Public Member Functions
size_type get_num_batch_items () const noexcept
Returns the number of items in the batch operator.
dim< 2 > get_common_size () const
Returns the common size of the batch items.
const batch_dim< 2 > & get_size () const noexcept
Returns the size of the batch operator.
template<typename ValueType >
void validate_application_parameters (const MultiVector< ValueType > *b, MultiVector< ValueType > *x) const
Validates the sizes for the apply(b,x) operation in the concrete BatchLinOp.
template<typename ValueType >
void validate_application_parameters (const MultiVector< ValueType > *alpha, const MultiVector< ValueType > *b, const MultiVector< ValueType > *beta, MultiVector< ValueType > *x) const
Validates the sizes for the apply(alpha, b , beta, x) operation in the concrete BatchLinOp.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< BatchLinOp >
std::unique_ptr< BatchLinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > create_default () const
std::unique_ptr< BatchLinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< BatchLinOp > clone () const
BatchLinOp * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, BatchLinOp > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, BatchLinOp > * copy_from (const std::unique_ptr< Derived > &other)
BatchLinOp * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
BatchLinOp * move_from (ptr_param< PolymorphicObject > other)
BatchLinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (std::unique_ptr< Derived, Deleter > &&other)
Moves another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (const std::unique_ptr< Derived, Deleter > &other)
Copies another object into this object.
PolymorphicObject * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Copies another object into this object.
PolymorphicObject * move_from (ptr_param< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
void remove_logger (ptr_param< const Logger > logger)
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::log::Loggable
void remove_logger (ptr_param< const Logger > logger)
Member Function Documentation
get_common_size()
dim<2> gko::batch::BatchLinOp::get_common_size () const inline
Returns the common size of the batch items.
Returns
the common size stored
References gko::batch_dim< Dimensionality, DimensionType >::get_common_size(), and get_size().
Referenced by validate_application_parameters().
get_num_batch_items()
size_type gko::batch::BatchLinOp::get_num_batch_items () const inline noexcept
Returns the number of items in the batch operator.
Returns
number of items in the batch operator
References gko::batch_dim< Dimensionality, DimensionType >::get_num_batch_items(), and get_size().
Referenced by validate_application_parameters().
get_size()
const batch_dim<2>& gko::batch::BatchLinOp::get_size () const inline noexcept
Returns the size of the batch operator.
Returns
size of the batch operator, a batch_dim object
Referenced by get_common_size(), and get_num_batch_items().
The documentation for this class was generated from the following file:
ginkgo/core/base/batch_lin_op.hpp