Ginkgo: gko::matrix::Sellp< ValueType, IndexType > Class Template Reference
gko::matrix::Sellp< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
SELL-P is a matrix format similar to ELL format.
#include <ginkgo/core/matrix/sellp.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using mat_data = matrix_data< ValueType, IndexType >
using device_mat_data = device_matrix_data< ValueType, IndexType >
using absolute_type = remove_complex< Sellp >
Public Types inherited from gko::EnablePolymorphicAssignment< Sellp< ValueType, IndexType > >
using result_type = Sellp< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Sellp< ValueType, IndexType > >
using result_type = Sellp< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Sellp< next_precision< ValueType >, IndexType > >
using result_type = Sellp< next_precision< ValueType >, IndexType >
Public Types inherited from gko::ConvertibleTo< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
using result_type = Csr< ValueType, IndexType >
Public Types inherited from gko::DiagonalExtractable< ValueType >
using value_type = ValueType
Public Types inherited from gko::ReadableFromMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Types inherited from gko::WritableToMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Types inherited from gko::EnableAbsoluteComputation< remove_complex< Sellp< ValueType, IndexType > > >
using absolute_type = remove_complex< Sellp< ValueType, IndexType > >
Public Member Functions
void convert_to (Sellp< next_precision< ValueType >, IndexType > *result) const override
void move_to (Sellp< next_precision< ValueType >, IndexType > *result) override
void convert_to (Dense< ValueType > *other) const override
void move_to (Dense< ValueType > *other) override
void convert_to (Csr< ValueType, IndexType > *other) const override
void move_to (Csr< ValueType, IndexType > *other) override
void read (const mat_data &data) override
Reads a matrix from a matrix_data structure.
void read (const device_mat_data &data) override
Reads a matrix from a device_matrix_data structure.
void read (device_mat_data &&data) override
Reads a matrix from a device_matrix_data structure.
void write (mat_data &data) const override
Writes a matrix to a matrix_data structure.
std::unique_ptr< Diagonal< ValueType > > extract_diagonal () const override
Extracts the diagonal entries of the matrix into a vector.
std::unique_ptr< absolute_type > compute_absolute () const override
Gets the AbsoluteLinOp.
void compute_absolute_inplace () override
Compute absolute inplace on each element.
value_type * get_values () noexcept
Returns the values of the matrix.
const value_type * get_const_values () const noexcept
Returns the values of the matrix.
index_type * get_col_idxs () noexcept
Returns the column indexes of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indexes of the matrix.
size_type * get_slice_lengths () noexcept
Returns the lengths(columns) of slices.
const size_type * get_const_slice_lengths () const noexcept
Returns the lengths(columns) of slices.
size_type * get_slice_sets () noexcept
Returns the offsets of slices.
const size_type * get_const_slice_sets () const noexcept
Returns the offsets of slices.
size_type get_slice_size () const noexcept
Returns the size of a slice.
size_type get_stride_factor () const noexcept
Returns the stride factor(t) of SELL-P.
size_type get_total_cols () const noexcept
Returns the total column number.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix.
value_type & val_at (size_type row, size_type slice_set, size_type idx) noexcept
Returns the idx-th non-zero element of the row-th row with slice_set slice set.
value_type val_at (size_type row, size_type slice_set, size_type idx) const noexcept
Returns the idx-th non-zero element of the row-th row with slice_set slice set.
index_type & col_at (size_type row, size_type slice_set, size_type idx) noexcept
Returns the idx-th column index of the row-th row with slice_set slice set.
index_type col_at (size_type row, size_type slice_set, size_type idx) const noexcept
Returns the idx-th column index of the row-th row with slice_set slice set.
Sellp & operator= (const Sellp &)
Copy-assigns a Sellp matrix.
Sellp & operator= (Sellp &&)
Move-assigns a Sellp matrix.
Sellp (const Sellp &)
Copy-assigns a Sellp matrix.
Sellp (Sellp &&)
Move-assigns a Sellp matrix.
Public Member Functions inherited from gko::EnableLinOp< Sellp< ValueType, IndexType > >
const Sellp< ValueType, IndexType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
Sellp< ValueType, IndexType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
const Sellp< ValueType, IndexType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
Sellp< ValueType, IndexType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Sellp< ValueType, IndexType >, LinOp >
std::unique_ptr< Sellp< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Sellp< ValueType, IndexType > > create_default () const
std::unique_ptr< Sellp< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Sellp< ValueType, IndexType > > clone () const
Sellp< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, Sellp< ValueType, IndexType > > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, Sellp< ValueType, IndexType > > * copy_from (const std::unique_ptr< Derived > &other)
Sellp< ValueType, IndexType > * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Sellp< ValueType, IndexType > * move_from (ptr_param< PolymorphicObject > other)
Sellp< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
LinOp & operator= (const LinOp &)=default
Copy-assigns a LinOp.
LinOp & operator= (LinOp &&other)
Move-assigns a LinOp.
LinOp (const LinOp &)=default
Copy-constructs a LinOp.
LinOp (LinOp &&other)
Move-constructs a LinOp.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (const std::unique_ptr< Derived > &other)
LinOp * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
LinOp * move_from (ptr_param< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (std::unique_ptr< Derived, Deleter > &&other)
Moves another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (const std::unique_ptr< Derived, Deleter > &other)
Copies another object into this object.
PolymorphicObject * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Copies another object into this object.
PolymorphicObject * move_from (ptr_param< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
void remove_logger (ptr_param< const Logger > logger)
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::log::Loggable
void remove_logger (ptr_param< const Logger > logger)
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Sellp< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Sellp< ValueType, IndexType > >
void convert_to (ptr_param< result_type > result) const
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Sellp< next_precision< ValueType >, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Dense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::DiagonalExtractable< ValueType >
std::unique_ptr< LinOp > extract_diagonal_linop () const override
Extracts the diagonal entries of the matrix into a vector.
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, IndexType >
void read (const matrix_assembly_data< ValueType, IndexType > &data)
Reads a matrix from a matrix_assembly_data structure.
Public Member Functions inherited from gko::EnableAbsoluteComputation< remove_complex< Sellp< ValueType, IndexType > > >
std::unique_ptr< LinOp > compute_absolute_linop () const override
Gets the absolute LinOp.
Static Public Member Functions
static std::unique_ptr< Sellp > create (std::shared_ptr< const Executor > exec, const dim< 2 > &size={}, size_type total_cols=0)
Creates an uninitialized Sellp matrix of the specified size.
static std::unique_ptr< Sellp > create (std::shared_ptr< const Executor > exec, const dim< 2 > &size, size_type slice_size, size_type stride_factor, size_type total_cols)
Creates an uninitialized Sellp matrix of the specified size.
Friends
class EnablePolymorphicObject< Sellp, LinOp >
class Dense< ValueType >
class Csr< ValueType, IndexType >
class Sellp< to_complex< ValueType >, IndexType >
class Sellp< next_precision< ValueType >, IndexType >
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::Sellp< ValueType, IndexType >
SELL-P is a matrix format similar to ELL format.
The difference is that SELL-P format divides rows into smaller slices and store each slice with ELL format.
This implementation uses the column index value invalid_index<IndexType>() to mark padding entries that are not part of the sparsity pattern.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes
Constructor & Destructor Documentation
Sellp() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Sellp< ValueType, IndexType >::Sellp (const Sellp< ValueType, IndexType > &)
Copy-assigns a Sellp matrix.
Inherits the executor, copies the data and parameters.
Sellp() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::Sellp< ValueType, IndexType >::Sellp (Sellp< ValueType, IndexType > &&)
Move-assigns a Sellp matrix.
Inherits the executor, moves the data and parameters. The moved-from object is empty (0x0 with valid slice_sets and unchanged parameters).
Member Function Documentation
col_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type gko::matrix::Sellp< ValueType, IndexType >::col_at (size_type row, size_type slice_set, size_type idx) const inline noexcept
Returns the idx-th column index of the row-th row with slice_set slice set.
Parameters
row the row of the requested element in the slice
slice_set the slice set of the slice
idx the idx-th stored element of the row in the slice
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the CPU results in a runtime error)
col_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> index_type& gko::matrix::Sellp< ValueType, IndexType >::col_at (size_type row, size_type slice_set, size_type idx) inline noexcept
Returns the idx-th column index of the row-th row with slice_set slice set.
Parameters
row the row of the requested element in the slice
slice_set the slice set of the slice
idx the idx-th stored element of the row in the slice
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the CPU results in a runtime error)
References gko::matrix::Sellp< ValueType, IndexType >::get_col_idxs().
compute_absolute()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<absolute_type> gko::matrix::Sellp< ValueType, IndexType >::compute_absolute () const override virtual
Gets the AbsoluteLinOp.
Returns
a pointer to the new absolute object
Implements gko::EnableAbsoluteComputation< remove_complex< Sellp< ValueType, IndexType > > >.
create() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> static std::unique_ptr<Sellp> gko::matrix::Sellp< ValueType, IndexType >::create (std::shared_ptr< const Executor > exec, const dim< 2 > & size, size_type slice_size, size_type stride_factor, size_type total_cols) static
Creates an uninitialized Sellp matrix of the specified size.
Parameters
exec Executor associated to the matrix
size size of the matrix
slice_size number of rows in each slice
stride_factor factor for the stride in each slice (strides should be multiples of the stride_factor)
total_cols number of the sum of all cols in every slice.
Returns
A smart pointer to the newly created matrix.
create() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> static std::unique_ptr<Sellp> gko::matrix::Sellp< ValueType, IndexType >::create (std::shared_ptr< const Executor > exec, const dim< 2 > & size = {}, size_type total_cols = 0) static
Creates an uninitialized Sellp matrix of the specified size.
(The slice_size and stride_factor are set to the default values.)
Parameters
exec Executor associated to the matrix
size size of the matrix
total_cols number of the sum of all cols in every slice.
Returns
A smart pointer to the newly created matrix.
extract_diagonal()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<Diagonal<ValueType> > gko::matrix::Sellp< ValueType, IndexType >::extract_diagonal () const override virtual
Extracts the diagonal entries of the matrix into a vector.
Parameters
diag the vector into which the diagonal will be written
Implements gko::DiagonalExtractable< ValueType >.
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::Sellp< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
References gko::array< ValueType >::get_data().
Referenced by gko::matrix::Sellp< ValueType, IndexType >::col_at().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::Sellp< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indexes of the matrix.
Returns
the column indexes of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_const_slice_lengths()
template<typename ValueType = default_precision, typename IndexType = int32> const size_type* gko::matrix::Sellp< ValueType, IndexType >::get_const_slice_lengths () const inline noexcept
Returns the lengths(columns) of slices.
Returns
the lengths(columns) of slices.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_const_slice_sets()
template<typename ValueType = default_precision, typename IndexType = int32> const size_type* gko::matrix::Sellp< ValueType, IndexType >::get_const_slice_sets () const inline noexcept
Returns the offsets of slices.
Returns
the offsets of slices.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_const_values()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::Sellp< ValueType, IndexType >::get_const_values () const inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_num_stored_elements()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Sellp< ValueType, IndexType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::array< ValueType >::get_size().
get_slice_lengths()
template<typename ValueType = default_precision, typename IndexType = int32> size_type* gko::matrix::Sellp< ValueType, IndexType >::get_slice_lengths () inline noexcept
Returns the lengths(columns) of slices.
Returns
the lengths(columns) of slices.
References gko::array< ValueType >::get_data().
get_slice_sets()
template<typename ValueType = default_precision, typename IndexType = int32> size_type* gko::matrix::Sellp< ValueType, IndexType >::get_slice_sets () inline noexcept
Returns the offsets of slices.
Returns
the offsets of slices.
References gko::array< ValueType >::get_data().
get_slice_size()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Sellp< ValueType, IndexType >::get_slice_size () const inline noexcept
Returns the size of a slice.
Returns
the size of a slice.
get_stride_factor()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Sellp< ValueType, IndexType >::get_stride_factor () const inline noexcept
Returns the stride factor(t) of SELL-P.
Returns
the stride factor(t) of SELL-P.
get_total_cols()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::Sellp< ValueType, IndexType >::get_total_cols () const inline noexcept
Returns the total column number.
Returns
the total column number.
References gko::array< ValueType >::get_size().
get_values()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::Sellp< ValueType, IndexType >::get_values () inline noexcept
Returns the values of the matrix.
Returns
the values of the matrix.
References gko::array< ValueType >::get_data().
operator=() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> Sellp& gko::matrix::Sellp< ValueType, IndexType >::operator= (const Sellp< ValueType, IndexType > &)
Copy-assigns a Sellp matrix.
Preserves the executor, copies the data and parameters.
operator=() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> Sellp& gko::matrix::Sellp< ValueType, IndexType >::operator= (Sellp< ValueType, IndexType > &&)
Move-assigns a Sellp matrix.
Preserves the executor, moves the data and parameters. The moved-from object is empty (0x0 with valid slice_sets and unchanged parameters).
read() [1/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Sellp< ValueType, IndexType >::read (const device_mat_data & data) override virtual
Reads a matrix from a device_matrix_data structure.
Parameters
data the device_matrix_data structure.
Reimplemented from gko::ReadableFromMatrixData< ValueType, IndexType >.
read() [2/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Sellp< ValueType, IndexType >::read (const mat_data & data) override virtual
Reads a matrix from a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::ReadableFromMatrixData< ValueType, IndexType >.
read() [3/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Sellp< ValueType, IndexType >::read (device_mat_data && data) override virtual
Reads a matrix from a device_matrix_data structure.
The structure may be emptied by this function.
Parameters
data the device_matrix_data structure.
Reimplemented from gko::ReadableFromMatrixData< ValueType, IndexType >.
val_at() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type gko::matrix::Sellp< ValueType, IndexType >::val_at (size_type row, size_type slice_set, size_type idx) const inline noexcept
Returns the idx-th non-zero element of the row-th row with slice_set slice set.
Parameters
row the row of the requested element in the slice
slice_set the slice set of the slice
idx the idx-th stored element of the row in the slice
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the CPU results in a runtime error)
References gko::array< ValueType >::get_const_data().
val_at() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> value_type& gko::matrix::Sellp< ValueType, IndexType >::val_at (size_type row, size_type slice_set, size_type idx) inline noexcept
Returns the idx-th non-zero element of the row-th row with slice_set slice set.
Parameters
row the row of the requested element in the slice
slice_set the slice set of the slice
idx the idx-th stored element of the row in the slice
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the CPU results in a runtime error)
References gko::array< ValueType >::get_data().
write()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::Sellp< ValueType, IndexType >::write (mat_data & data) const override virtual
Writes a matrix to a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::WritableToMatrixData< ValueType, IndexType >.
The documentation for this class was generated from the following files:
ginkgo/core/matrix/csr.hpp
ginkgo/core/matrix/sellp.hpp