Ginkgo: gko::matrix::Dense< ValueType > Class Template Reference
gko::matrix::Dense< ValueType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
Dense is a matrix format which explicitly stores all values of the matrix.
#include <ginkgo/core/matrix/dense.hpp>
Public Types
using value_type = ValueType
using index_type = int64
using transposed_type = Dense< ValueType >
using mat_data = matrix_data< ValueType, int64 >
using mat_data32 = matrix_data< ValueType, int32 >
using device_mat_data = device_matrix_data< ValueType, int64 >
using device_mat_data32 = device_matrix_data< ValueType, int32 >
using absolute_type = remove_complex< Dense >
using real_type = absolute_type
using complex_type = to_complex< Dense >
using row_major_range = gko::range< gko::accessor::row_major< ValueType, 2 > >
Public Types inherited from gko::EnablePolymorphicAssignment< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Types inherited from gko::ConvertibleTo< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Types inherited from gko::ConvertibleTo< Dense< next_precision< ValueType > > >
using result_type = Dense< next_precision< ValueType > >
Public Types inherited from gko::ConvertibleTo< Coo< ValueType, int32 > >
using result_type = Coo< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Coo< ValueType, int64 > >
using result_type = Coo< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, int32 > >
using result_type = Csr< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, int64 > >
using result_type = Csr< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Ell< ValueType, int32 > >
using result_type = Ell< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Ell< ValueType, int64 > >
using result_type = Ell< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Fbcsr< ValueType, int32 > >
using result_type = Fbcsr< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Fbcsr< ValueType, int64 > >
using result_type = Fbcsr< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Hybrid< ValueType, int32 > >
using result_type = Hybrid< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Hybrid< ValueType, int64 > >
using result_type = Hybrid< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Sellp< ValueType, int32 > >
using result_type = Sellp< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Sellp< ValueType, int64 > >
using result_type = Sellp< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< SparsityCsr< ValueType, int32 > >
using result_type = SparsityCsr< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< SparsityCsr< ValueType, int64 > >
using result_type = SparsityCsr< ValueType, int64 >
Public Types inherited from gko::DiagonalExtractable< ValueType >
using value_type = ValueType
Public Types inherited from gko::ReadableFromMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::ReadableFromMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::WritableToMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::WritableToMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::EnableAbsoluteComputation< remove_complex< Dense< ValueType > > >
using absolute_type = remove_complex< Dense< ValueType > >
Public Member Functions
void convert_to (Dense< next_precision< ValueType >> *result) const override
void move_to (Dense< next_precision< ValueType >> *result) override
void convert_to (Coo< ValueType, int32 > *result) const override
void move_to (Coo< ValueType, int32 > *result) override
void convert_to (Coo< ValueType, int64 > *result) const override
void move_to (Coo< ValueType, int64 > *result) override
void convert_to (Csr< ValueType, int32 > *result) const override
void move_to (Csr< ValueType, int32 > *result) override
void convert_to (Csr< ValueType, int64 > *result) const override
void move_to (Csr< ValueType, int64 > *result) override
void convert_to (Ell< ValueType, int32 > *result) const override
void move_to (Ell< ValueType, int32 > *result) override
void convert_to (Ell< ValueType, int64 > *result) const override
void move_to (Ell< ValueType, int64 > *result) override
void convert_to (Fbcsr< ValueType, int32 > *result) const override
void move_to (Fbcsr< ValueType, int32 > *result) override
void convert_to (Fbcsr< ValueType, int64 > *result) const override
void move_to (Fbcsr< ValueType, int64 > *result) override
void convert_to (Hybrid< ValueType, int32 > *result) const override
void move_to (Hybrid< ValueType, int32 > *result) override
void convert_to (Hybrid< ValueType, int64 > *result) const override
void move_to (Hybrid< ValueType, int64 > *result) override
void convert_to (Sellp< ValueType, int32 > *result) const override
void move_to (Sellp< ValueType, int32 > *result) override
void convert_to (Sellp< ValueType, int64 > *result) const override
void move_to (Sellp< ValueType, int64 > *result) override
void convert_to (SparsityCsr< ValueType, int32 > *result) const override
void move_to (SparsityCsr< ValueType, int32 > *result) override
void convert_to (SparsityCsr< ValueType, int64 > *result) const override
void move_to (SparsityCsr< ValueType, int64 > *result) override
void read (const mat_data &data) override
void read (const mat_data32 &data) override
void read (const device_mat_data &data) override
void read (const device_mat_data32 &data) override
void read (device_mat_data &&data) override
void read (device_mat_data32 &&data) override
void write (mat_data &data) const override
void write (mat_data32 &data) const override
std::unique_ptr< LinOp > transpose () const override
Returns a LinOp representing the transpose of the Transposable object.
std::unique_ptr< LinOp > conj_transpose () const override
Returns a LinOp representing the conjugate transpose of the Transposable object.
void transpose (Dense *output) const
Writes the transposed matrix into the given output matrix.
void conj_transpose (Dense *output) const
Writes the conjugate-transposed matrix into the given output matrix.
void fill (const ValueType value)
Fill the dense matrix with a given value.
std::unique_ptr< LinOp > permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the symmetric row and column permutation of the Permutable object.
std::unique_ptr< LinOp > permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the symmetric row and column permutation of the Permutable object.
void permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the symmetrically permuted matrix into the given output matrix.
void permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< LinOp > inverse_permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the symmetric inverse row and column permutation of the Permutable object.
std::unique_ptr< LinOp > inverse_permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the symmetric inverse row and column permutation of the Permutable object.
void inverse_permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the inverse symmetrically permuted matrix into the given output matrix.
void inverse_permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< LinOp > row_permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the Permutable object.
std::unique_ptr< LinOp > row_permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the Permutable object.
void row_permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the row-permuted matrix into the given output matrix.
void row_permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< Dense > row_gather (const array< int32 > *gather_indices) const
Create a Dense matrix consisting of the given rows from this matrix.
std::unique_ptr< Dense > row_gather (const array< int64 > *gather_indices) const
Create a Dense matrix consisting of the given rows from this matrix.
void row_gather (const array< int32 > *gather_indices, Dense *row_collection) const
Copies the given rows from this matrix into row_collection
void row_gather (const array< int64 > *gather_indices, Dense *row_collection) const
Copies the given rows from this matrix into row_collection
void row_gather (const array< int32 > *gather_indices, LinOp *row_collection) const
Copies the given rows from this matrix into row_collection
void row_gather (const array< int64 > *gather_indices, LinOp *row_collection) const
Copies the given rows from this matrix into row_collection
void row_gather (const LinOp *alpha, const array< int32 > *gather_indices, const LinOp *beta, LinOp *row_collection) const
Copies the given rows from this matrix into row_collection with scaling.
void row_gather (const LinOp *alpha, const array< int64 > *gather_indices, const LinOp *beta, LinOp *row_collection) const
std::unique_ptr< LinOp > column_permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the column permutation of the Permutable object.
std::unique_ptr< LinOp > column_permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the column permutation of the Permutable object.
void column_permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the column-permuted matrix into the given output matrix.
void column_permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< LinOp > inverse_row_permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the inverse permuted object.
std::unique_ptr< LinOp > inverse_row_permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the inverse permuted object.
void inverse_row_permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the inverse row-permuted matrix into the given output matrix.
void inverse_row_permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< LinOp > inverse_column_permute (const array< int32 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the inverse permuted object.
std::unique_ptr< LinOp > inverse_column_permute (const array< int64 > *permutation_indices) const override
Returns a LinOp representing the row permutation of the inverse permuted object.
void inverse_column_permute (const array< int32 > *permutation_indices, Dense *output) const
Writes the inverse column-permuted matrix into the given output matrix.
void inverse_column_permute (const array< int64 > *permutation_indices, Dense *output) const
std::unique_ptr< Diagonal< ValueType > > extract_diagonal () const override
Extracts the diagonal entries of the matrix into a vector.
void extract_diagonal (Diagonal< ValueType > *output) const
Writes the diagonal of this matrix into an existing diagonal matrix.
std::unique_ptr< absolute_type > compute_absolute () const override
Gets the AbsoluteLinOp.
void compute_absolute (absolute_type *output) const
Writes the absolute values of this matrix into an existing matrix.
void compute_absolute_inplace () override
Compute absolute inplace on each element.
std::unique_ptr< complex_type > make_complex () const
Creates a complex copy of the original matrix.
void make_complex (complex_type *result) const
Writes a complex copy of the original matrix to a given complex matrix.
std::unique_ptr< real_type > get_real () const
Creates a new real matrix and extracts the real part of the original matrix into that.
void get_real (real_type *result) const
Extracts the real part of the original matrix into a given real matrix.
std::unique_ptr< real_type > get_imag () const
Creates a new real matrix and extracts the imaginary part of the original matrix into that.
void get_imag (real_type *result) const
Extracts the imaginary part of the original matrix into a given real matrix.
value_type * get_values () noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values () const noexcept
Returns a pointer to the array of values of the matrix.
size_type get_stride () const noexcept
Returns the stride of the matrix.
size_type get_num_stored_elements () const noexcept
Returns the number of elements explicitly stored in the matrix.
value_type & at (size_type row, size_type col) noexcept
Returns a single element of the matrix.
value_type at (size_type row, size_type col) const noexcept
Returns a single element of the matrix.
ValueType & at (size_type idx) noexcept
Returns a single element of the matrix.
ValueType at (size_type idx) const noexcept
Returns a single element of the matrix.
void scale (const LinOp *alpha)
Scales the matrix with a scalar (aka: BLAS scal).
void inv_scale (const LinOp *alpha)
Scales the matrix with the inverse of a scalar.
void add_scaled (const LinOp *alpha, const LinOp *b)
Adds b scaled by alpha to the matrix (aka: BLAS axpy).
void sub_scaled (const LinOp *alpha, const LinOp *b)
Subtracts b scaled by alpha fron the matrix (aka: BLAS axpy).
void compute_dot (const LinOp *b, LinOp *result) const
Computes the column-wise dot product of this matrix and b.
void compute_dot (const LinOp *b, LinOp *result, array< char > &tmp) const
Computes the column-wise dot product of this matrix and b.
void compute_conj_dot (const LinOp *b, LinOp *result) const
Computes the column-wise dot product of conj(this matrix) and b.
void compute_conj_dot (const LinOp *b, LinOp *result, array< char > &tmp) const
Computes the column-wise dot product of conj(this matrix) and b.
void compute_norm2 (LinOp *result) const
Computes the column-wise Euclidian (L^2) norm of this matrix.
void compute_norm2 (LinOp *result, array< char > &tmp) const
Computes the column-wise Euclidian (L^2) norm of this matrix.
void compute_norm1 (LinOp *result) const
Computes the column-wise (L^1) norm of this matrix.
void compute_norm1 (LinOp *result, array< char > &tmp) const
Computes the column-wise (L^1) norm of this matrix.
std::unique_ptr< Dense > create_submatrix (const span &rows, const span &columns, const size_type stride)
Create a submatrix from the original matrix.
std::unique_ptr< Dense > create_submatrix (const span &rows, const span &columns)
Create a submatrix from the original matrix.
std::unique_ptr< real_type > create_real_view ()
Create a real view of the (potentially) complex original matrix.
std::unique_ptr< const real_type > create_real_view () const
Create a real view of the (potentially) complex original matrix.
Dense & operator= (const Dense &)
Copy-assigns a Dense matrix.
Dense & operator= (Dense &&)
Move-assigns a Dense matrix.
Dense (const Dense &)
Copy-constructs a Dense matrix.
Dense (Dense &&)
Move-constructs a Dense matrix.
Public Member Functions inherited from gko::EnableLinOp< Dense< ValueType > >
const Dense< ValueType > * apply (const LinOp *b, LinOp *x) const
Dense< ValueType > * apply (const LinOp *b, LinOp *x)
const Dense< ValueType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Dense< ValueType > * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Dense< ValueType >, LinOp >
std::unique_ptr< Dense< ValueType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Dense< ValueType > > create_default () const
std::unique_ptr< Dense< ValueType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Dense< ValueType > > clone () const
Dense< ValueType > * copy_from (const PolymorphicObject *other)
Dense< ValueType > * copy_from (std::unique_ptr< PolymorphicObject > other)
Dense< ValueType > * move_from (PolymorphicObject *other)
Dense< ValueType > * move_from (std::unique_ptr< PolymorphicObject > other)
Dense< ValueType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (const LinOp *b, LinOp *x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (const LinOp *b, LinOp *x) const
Applies a linear operator to a vector (or a sequence of vectors).
LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (const LinOp *alpha, const LinOp *b, const LinOp *beta, LinOp *x) const
Performs the operation x = alpha * op(b) + beta * x.
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
LinOp & operator= (const LinOp &)=default
Copy-assigns a LinOp.
LinOp & operator= (LinOp &&other)
Move-assigns a LinOp.
LinOp (const LinOp &)=default
Copy-constructs a LinOp.
LinOp (LinOp &&other)
Move-constructs a LinOp.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
LinOp * copy_from (std::unique_ptr< PolymorphicObject > other)
LinOp * move_from (PolymorphicObject *other)
LinOp * move_from (std::unique_ptr< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
PolymorphicObject * copy_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * move_from (PolymorphicObject *other)
Moves another object into this object.
PolymorphicObject * move_from (std::unique_ptr< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Dense< ValueType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Dense< next_precision< ValueType > > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Coo< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Coo< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Ell< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Ell< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Fbcsr< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Fbcsr< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Hybrid< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Hybrid< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Sellp< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Sellp< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< SparsityCsr< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< SparsityCsr< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::DiagonalExtractable< ValueType >
std::unique_ptr< LinOp > extract_diagonal_linop () const override
Extracts the diagonal entries of the matrix into a vector.
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, int32 >
virtual void read (const matrix_data< ValueType, int32 > &data)=0
Reads a matrix from a matrix_data structure.
void read (const matrix_assembly_data< ValueType, int32 > &data)
Reads a matrix from a matrix_assembly_data structure.
virtual void read (const device_matrix_data< ValueType, int32 > &data)
Reads a matrix from a device_matrix_data structure.
virtual void read (device_matrix_data< ValueType, int32 > &&data)
Reads a matrix from a device_matrix_data structure.
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, int64 >
virtual void read (const matrix_data< ValueType, int64 > &data)=0
Reads a matrix from a matrix_data structure.
void read (const matrix_assembly_data< ValueType, int64 > &data)
Reads a matrix from a matrix_assembly_data structure.
virtual void read (const device_matrix_data< ValueType, int64 > &data)
Reads a matrix from a device_matrix_data structure.
virtual void read (device_matrix_data< ValueType, int64 > &&data)
Reads a matrix from a device_matrix_data structure.
Public Member Functions inherited from gko::WritableToMatrixData< ValueType, int32 >
virtual void write (matrix_data< ValueType, int32 > &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::WritableToMatrixData< ValueType, int64 >
virtual void write (matrix_data< ValueType, int64 > &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::EnableAbsoluteComputation< remove_complex< Dense< ValueType > > >
std::unique_ptr< LinOp > compute_absolute_linop () const override
Gets the absolute LinOp.
Public Member Functions inherited from gko::ScaledIdentityAddable
void add_scaled_identity (const LinOp *const a, const LinOp *const b)
Scales this and adds another scalar times the identity to it.
Static Public Member Functions
static std::unique_ptr< Dense > create_with_config_of (const Dense *other)
Creates a Dense matrix with the same size and stride as another Dense matrix.
static std::unique_ptr< Dense > create_with_type_of (const Dense *other, std::shared_ptr< const Executor > exec, const dim< 2 > &size=dim< 2 >{})
Creates a Dense matrix with the same type and executor as another Dense matrix but a different size.
static std::unique_ptr< Dense > create_with_type_of (const Dense *other, std::shared_ptr< const Executor > exec, const dim< 2 > &size, size_type stride)
static std::unique_ptr< const Dense > create_const (std::shared_ptr< const Executor > exec, const dim< 2 > &size, gko::detail::const_array_view< ValueType > &&values, size_type stride)
Creates a constant (immutable) Dense matrix from a constant array.
Static Public Member Functions inherited from gko::EnableCreateMethod< Dense< ValueType > >
static std::unique_ptr< Dense< ValueType > > create (Args &&... args)
Friends
class EnableCreateMethod< Dense >
class EnablePolymorphicObject< Dense, LinOp >
class Coo< ValueType, int32 >
class Coo< ValueType, int64 >
class Csr< ValueType, int32 >
class Csr< ValueType, int64 >
class Diagonal< ValueType >
class Ell< ValueType, int32 >
class Ell< ValueType, int64 >
class Fbcsr< ValueType, int32 >
class Fbcsr< ValueType, int64 >
class Hybrid< ValueType, int32 >
class Hybrid< ValueType, int64 >
class Sellp< ValueType, int32 >
class Sellp< ValueType, int64 >
class SparsityCsr< ValueType, int32 >
class SparsityCsr< ValueType, int64 >
class Dense< to_complex< ValueType > >
class Dense< next_precision< ValueType > >
Detailed Description
template<typename ValueType = default_precision>
class gko::matrix::Dense< ValueType >
Dense is a matrix format which explicitly stores all values of the matrix.
The values are stored in row-major format (values belonging to the same row appear consecutive in the memory). Optionally, rows can be padded for better memory access.
Template Parameters
ValueType precision of matrix elements
Note
While this format is not very useful for storing sparse matrices, it is often suitable to store vectors, and sets of vectors.
Constructor & Destructor Documentation
Dense() [1/2]
template<typename ValueType = default_precision> gko::matrix::Dense< ValueType >::Dense (const Dense< ValueType > &)
Copy-constructs a Dense matrix.
Inherits executor and dimensions, but copies data without padding.
Dense() [2/2]
template<typename ValueType = default_precision> gko::matrix::Dense< ValueType >::Dense (Dense< ValueType > &&)
Move-constructs a Dense matrix.
Inherits executor, dimensions and data with padding. The moved-from object is empty (0x0 with empty Array).
Member Function Documentation
add_scaled()
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::add_scaled (const LinOp * alpha, const LinOp * b)
Adds b scaled by alpha to the matrix (aka: BLAS axpy).
Parameters
alpha If alpha is 1x1 Dense matrix, the entire matrix is scaled by alpha. If it is a Dense row vector of values, then i-th column of the matrix is scaled with the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
b a matrix of the same dimension as this
at() [1/4]
template<typename ValueType = default_precision> ValueType gko::matrix::Dense< ValueType >::at (size_type idx) const inline noexcept
Returns a single element of the matrix.
Useful for iterating across all elements of the matrix. However, it is less efficient than the two-parameter variant of this method.
Parameters
idx a linear index of the requested element (ignoring the stride)
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::array< ValueType >::get_const_data().
at() [2/4]
template<typename ValueType = default_precision> ValueType& gko::matrix::Dense< ValueType >::at (size_type idx) inline noexcept
Returns a single element of the matrix.
Useful for iterating across all elements of the matrix. However, it is less efficient than the two-parameter variant of this method.
Parameters
idx a linear index of the requested element (ignoring the stride)
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::array< ValueType >::get_data().
at() [3/4]
template<typename ValueType = default_precision> value_type gko::matrix::Dense< ValueType >::at (size_type row, size_type col) const inline noexcept
Returns a single element of the matrix.
Parameters
row the row of the requested element
col the column of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::array< ValueType >::get_const_data().
at() [4/4]
template<typename ValueType = default_precision> value_type& gko::matrix::Dense< ValueType >::at (size_type row, size_type col) inline noexcept
Returns a single element of the matrix.
Parameters
row the row of the requested element
col the column of the requested element
Note
the method has to be called on the same Executor the matrix is stored at (e.g. trying to call this method on a GPU matrix from the OMP results in a runtime error)
References gko::array< ValueType >::get_data().
Referenced by gko::initialize().
column_permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::column_permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the column permutation of the Permutable object.
In the resulting LinOp, the column i contains the input column perm[i].
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new column permuted object
Implements gko::Permutable< int32 >.
column_permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::column_permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the column-permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[1] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::column_permute(const array<int32>*)
column_permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::column_permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the column permutation of the Permutable object.
In the resulting LinOp, the column i contains the input column perm[i].
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new column permuted object
Implements gko::Permutable< int64 >.
column_permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::column_permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
compute_absolute() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<absolute_type> gko::matrix::Dense< ValueType >::compute_absolute () const override virtual
Gets the AbsoluteLinOp.
Returns
a pointer to the new absolute object
Implements gko::EnableAbsoluteComputation< remove_complex< Dense< ValueType > > >.
compute_absolute() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_absolute (absolute_type * output) const
Writes the absolute values of this matrix into an existing matrix.
Parameters
output The output matrix. Its size must match the size of this matrix.
See also
Dense::compute_absolute()
compute_conj_dot() [1/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_conj_dot (const LinOp * b, LinOp * result) const
Computes the column-wise dot product of conj(this matrix) and b.
Parameters
b a Dense matrix of same dimension as this
result a Dense row vector, used to store the dot product (the number of column in the vector must match the number of columns of this)
compute_conj_dot() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_conj_dot (const LinOp * b, LinOp * result, array< char > & tmp) const
Computes the column-wise dot product of conj(this matrix) and b.
Parameters
b a Dense matrix of same dimension as this
result a Dense row vector, used to store the dot product (the number of column in the vector must match the number of columns of this)
tmp the temporary storage to use for partial sums during the reduction computation. It may be resized and/or reset to the correct executor.
compute_dot() [1/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_dot (const LinOp * b, LinOp * result) const
Computes the column-wise dot product of this matrix and b.
Parameters
b a Dense matrix of same dimension as this
result a Dense row vector, used to store the dot product (the number of column in the vector must match the number of columns of this)
compute_dot() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_dot (const LinOp * b, LinOp * result, array< char > & tmp) const
Computes the column-wise dot product of this matrix and b.
Parameters
b a Dense matrix of same dimension as this
result a Dense row vector, used to store the dot product (the number of column in the vector must match the number of columns of this)
tmp the temporary storage to use for partial sums during the reduction computation. It may be resized and/or reset to the correct executor.
compute_norm1() [1/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_norm1 (LinOp * result) const
Computes the column-wise (L^1) norm of this matrix.
Parameters
result a Dense row vector, used to store the norm (the number of columns in the vector must match the number of columns of this)
compute_norm1() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_norm1 (LinOp * result, array< char > & tmp) const
Computes the column-wise (L^1) norm of this matrix.
Parameters
result a Dense row vector, used to store the norm (the number of columns in the vector must match the number of columns of this)
tmp the temporary storage to use for partial sums during the reduction computation. It may be resized and/or reset to the correct executor.
compute_norm2() [1/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_norm2 (LinOp * result) const
Computes the column-wise Euclidian (L^2) norm of this matrix.
Parameters
result a Dense row vector, used to store the norm (the number of columns in the vector must match the number of columns of this)
compute_norm2() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::compute_norm2 (LinOp * result, array< char > & tmp) const
Computes the column-wise Euclidian (L^2) norm of this matrix.
Parameters
result a Dense row vector, used to store the norm (the number of columns in the vector must match the number of columns of this)
tmp the temporary storage to use for partial sums during the reduction computation. It may be resized and/or reset to the correct executor.
conj_transpose() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::conj_transpose () const override virtual
Returns a LinOp representing the conjugate transpose of the Transposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::Transposable.
conj_transpose() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::conj_transpose (Dense< ValueType > * output) const
Writes the conjugate-transposed matrix into the given output matrix.
Parameters
output The output matrix. It must have the dimensions gko::transpose(this->get_size())
create_const()
template<typename ValueType = default_precision> static std::unique_ptr<const Dense> gko::matrix::Dense< ValueType >::create_const (std::shared_ptr< const Executor > exec, const dim< 2 > & size, gko::detail::const_array_view< ValueType > && values, size_type stride) inline static
Creates a constant (immutable) Dense matrix from a constant array.
Parameters
exec the executor to create the matrix on
size the dimensions of the matrix
values the value array of the matrix
stride the row-stride of the matrix
Returns
A smart pointer to the constant matrix wrapping the input array (if it resides on the same executor as the matrix) or a copy of the array on the correct executor.
create_real_view() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<real_type> gko::matrix::Dense< ValueType >::create_real_view ()
Create a real view of the (potentially) complex original matrix.
If the original matrix is real, nothing changes. If the original matrix is complex, the result is created by viewing the complex matrix with as real with a reinterpret_cast with twice the number of columns and double the stride.
create_real_view() [2/2]
template<typename ValueType = default_precision> std::unique_ptr<const real_type> gko::matrix::Dense< ValueType >::create_real_view () const
Create a real view of the (potentially) complex original matrix.
If the original matrix is real, nothing changes. If the original matrix is complex, the result is created by viewing the complex matrix with as real with a reinterpret_cast with twice the number of columns and double the stride.
create_submatrix() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::create_submatrix (const span & rows, const span & columns) inline
Create a submatrix from the original matrix.
Parameters
rows row span
columns column span
References gko::matrix::Dense< ValueType >::create_submatrix(), and gko::matrix::Dense< ValueType >::get_stride().
create_submatrix() [2/2]
template<typename ValueType = default_precision> std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::create_submatrix (const span & rows, const span & columns, const size_type stride) inline
Create a submatrix from the original matrix.
Warning: defining stride for this create_submatrix method might cause wrong memory access. Better use the create_submatrix(rows, columns) method instead.
Parameters
rows row span
columns column span
stride stride of the new submatrix.
Referenced by gko::matrix::Dense< ValueType >::create_submatrix().
create_with_config_of()
template<typename ValueType = default_precision> static std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::create_with_config_of (const Dense< ValueType > * other) inline static
Creates a Dense matrix with the same size and stride as another Dense matrix.
Parameters
other The other matrix whose configuration needs to copied.
create_with_type_of() [1/2]
template<typename ValueType = default_precision> static std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::create_with_type_of (const Dense< ValueType > * other, std::shared_ptr< const Executor > exec, const dim< 2 > & size, size_type stride) inline static
Parameters
stride The stride of the new matrix.
Note
This is an overload which allows full parameter specification.
create_with_type_of() [2/2]
template<typename ValueType = default_precision> static std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::create_with_type_of (const Dense< ValueType > * other, std::shared_ptr< const Executor > exec, const dim< 2 > & size = dim<2>{}) inline static
Creates a Dense matrix with the same type and executor as another Dense matrix but a different size.
Parameters
other The other matrix whose type we target.
exec The executor of the new matrix.
size The size of the new matrix.
stride The stride of the new matrix.
Returns
a Dense matrix with the type of other.
extract_diagonal() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<Diagonal<ValueType> > gko::matrix::Dense< ValueType >::extract_diagonal () const override virtual
Extracts the diagonal entries of the matrix into a vector.
Parameters
diag the vector into which the diagonal will be written
Implements gko::DiagonalExtractable< ValueType >.
extract_diagonal() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::extract_diagonal (Diagonal< ValueType > * output) const
Writes the diagonal of this matrix into an existing diagonal matrix.
Parameters
output The output matrix. Its size must match the size of this matrix's diagonal.
See also
Dense::extract_diagonal()
fill()
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::fill (const ValueType value)
Fill the dense matrix with a given value.
Parameters
value the value to be filled
get_const_values()
template<typename ValueType = default_precision> const value_type* gko::matrix::Dense< ValueType >::get_const_values () const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_num_stored_elements()
template<typename ValueType = default_precision> size_type gko::matrix::Dense< ValueType >::get_num_stored_elements () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::array< ValueType >::get_num_elems().
get_stride()
template<typename ValueType = default_precision> size_type gko::matrix::Dense< ValueType >::get_stride () const inline noexcept
Returns the stride of the matrix.
Returns
the stride of the matrix.
Referenced by gko::matrix::Dense< ValueType >::create_submatrix().
get_values()
template<typename ValueType = default_precision> value_type* gko::matrix::Dense< ValueType >::get_values () inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
References gko::array< ValueType >::get_data().
inv_scale()
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inv_scale (const LinOp * alpha)
Scales the matrix with the inverse of a scalar.
Parameters
alpha If alpha is 1x1 Dense matrix, the entire matrix is scaled by 1 / alpha. If it is a Dense row vector of values, then i-th column of the matrix is scaled with the inverse of the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
inverse_column_permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_column_permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the inverse permuted object.
In the resulting LinOp, the column perm[i] contains the input column i.
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new inverse permuted object
Implements gko::Permutable< int32 >.
inverse_column_permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_column_permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the inverse column-permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[1] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::inverse_column_permute(const array<int32>*)
inverse_column_permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_column_permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the inverse permuted object.
In the resulting LinOp, the column perm[i] contains the input column i.
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new inverse permuted object
Implements gko::Permutable< int64 >.
inverse_column_permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_column_permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
inverse_permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the symmetric inverse row and column permutation of the Permutable object.
In the resulting LinOp, the entry at location (perm[i],perm[j]) contains the input value (i,j).
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Reimplemented from gko::Permutable< int32 >.
inverse_permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the inverse symmetrically permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[0] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::inverse_permute(const array<int32>*)
inverse_permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the symmetric inverse row and column permutation of the Permutable object.
In the resulting LinOp, the entry at location (perm[i],perm[j]) contains the input value (i,j).
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Reimplemented from gko::Permutable< int64 >.
inverse_permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
inverse_row_permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_row_permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the inverse permuted object.
In the resulting LinOp, the row perm[i] contains the input row i.
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new inverse permuted object
Implements gko::Permutable< int32 >.
inverse_row_permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_row_permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the inverse row-permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[0] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::inverse_row_permute(const array<int32>*)
inverse_row_permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::inverse_row_permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the inverse permuted object.
In the resulting LinOp, the row perm[i] contains the input row i.
Parameters
permutation_indices the array of indices containing the permutation order perm.
Returns
a pointer to the new inverse permuted object
Implements gko::Permutable< int64 >.
inverse_row_permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::inverse_row_permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
make_complex() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<complex_type> gko::matrix::Dense< ValueType >::make_complex () const
Creates a complex copy of the original matrix.
If the original matrix was real, the imaginary part of the result will be zero.
make_complex() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::make_complex (complex_type * result) const
Writes a complex copy of the original matrix to a given complex matrix.
If the original matrix was real, the imaginary part of the result will be zero.
operator=() [1/2]
template<typename ValueType = default_precision> Dense& gko::matrix::Dense< ValueType >::operator= (const Dense< ValueType > &)
Copy-assigns a Dense matrix.
Preserves the executor, reallocates the matrix with minimal stride if the dimensions don't match, then copies the data over, ignoring padding.
operator=() [2/2]
template<typename ValueType = default_precision> Dense& gko::matrix::Dense< ValueType >::operator= (Dense< ValueType > &&)
Move-assigns a Dense matrix.
Preserves the executor, moves the data over preserving size and stride. Leaves the moved-from object in an empty state (0x0 with empty Array).
permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the symmetric row and column permutation of the Permutable object.
In the resulting LinOp, the entry at location (i,j) contains the input value (perm[i],perm[j]).
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Reimplemented from gko::Permutable< int32 >.
permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the symmetrically permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[0] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::permute(const array<int32>*)
permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the symmetric row and column permutation of the Permutable object.
In the resulting LinOp, the entry at location (i,j) contains the input value (perm[i],perm[j]).
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Reimplemented from gko::Permutable< int64 >.
permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
row_gather() [1/8]
template<typename ValueType = default_precision> std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::row_gather (const array< int32 > * gather_indices) const
Create a Dense matrix consisting of the given rows from this matrix.
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
Returns
Dense matrix on the same executor with the same number of columns and gather_indices->get_num_elems() rows containing the gathered rows from this matrix: output(i,j) = input(gather_indices(i), j)
row_gather() [2/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const array< int32 > * gather_indices, Dense< ValueType > * row_collection) const
Copies the given rows from this matrix into row_collection
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
row_collection pointer to a Dense matrix that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_gather() [3/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const array< int32 > * gather_indices, LinOp * row_collection) const
Copies the given rows from this matrix into row_collection
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
row_collection pointer to a LinOp that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_gather() [4/8]
template<typename ValueType = default_precision> std::unique_ptr<Dense> gko::matrix::Dense< ValueType >::row_gather (const array< int64 > * gather_indices) const
Create a Dense matrix consisting of the given rows from this matrix.
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
Returns
Dense matrix on the same executor with the same number of columns and gather_indices->get_num_elems() rows containing the gathered rows from this matrix: output(i,j) = input(gather_indices(i), j)
row_gather() [5/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const array< int64 > * gather_indices, Dense< ValueType > * row_collection) const
Copies the given rows from this matrix into row_collection
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
row_collection pointer to a Dense matrix that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_gather() [6/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const array< int64 > * gather_indices, LinOp * row_collection) const
Copies the given rows from this matrix into row_collection
Parameters
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
row_collection pointer to a LinOp that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_gather() [7/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const LinOp * alpha, const array< int32 > * gather_indices, const LinOp * beta, LinOp * row_collection) const
Copies the given rows from this matrix into row_collection with scaling.
Parameters
alpha scaling the result of row gathering
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
beta scaling the input row_collection
row_collection pointer to a LinOp that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_gather() [8/8]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_gather (const LinOp * alpha, const array< int64 > * gather_indices, const LinOp * beta, LinOp * row_collection) const
Parameters
alpha scaling the result of row gathering
gather_indices pointer to an array containing row indices from this matrix. It may contain duplicates.
beta scaling the input row_collection
row_collection pointer to a LinOp that will store the gathered rows: row_collection(i,j) = input(gather_indices(i), j) It must have the same number of columns as this matrix and gather_indices->get_num_elems() rows.
row_permute() [1/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::row_permute (const array< int32 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the Permutable object.
In the resulting LinOp, the row i contains the input row perm[i].
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Implements gko::Permutable< int32 >.
row_permute() [2/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_permute (const array< int32 > * permutation_indices, Dense< ValueType > * output) const
Writes the row-permuted matrix into the given output matrix.
Parameters
permutation_indices The array containing permutation indices. It must have this->get_size()[0] elements.
output The output matrix. It must have the dimensions this->get_size()
See also
Dense::row_permute(const array<int32>*)
row_permute() [3/4]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::row_permute (const array< int64 > * permutation_indices) const override virtual
Returns a LinOp representing the row permutation of the Permutable object.
In the resulting LinOp, the row i contains the input row perm[i].
Parameters
permutation_indices the array of indices containing the permutation order.
Returns
a pointer to the new permuted object
Implements gko::Permutable< int64 >.
row_permute() [4/4]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::row_permute (const array< int64 > * permutation_indices, Dense< ValueType > * output) const
scale()
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::scale (const LinOp * alpha)
Scales the matrix with a scalar (aka: BLAS scal).
Parameters
alpha If alpha is 1x1 Dense matrix, the entire matrix is scaled by alpha. If it is a Dense row vector of values, then i-th column of the matrix is scaled with the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
sub_scaled()
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::sub_scaled (const LinOp * alpha, const LinOp * b)
Subtracts b scaled by alpha fron the matrix (aka: BLAS axpy).
Parameters
alpha If alpha is 1x1 Dense matrix, b is scaled by alpha. If it is a Dense row vector of values, then i-th column of b is scaled with the i-th element of alpha (the number of columns of alpha has to match the number of columns of the matrix).
b a matrix of the same dimension as this
transpose() [1/2]
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Dense< ValueType >::transpose () const override virtual
Returns a LinOp representing the transpose of the Transposable object.
Returns
a pointer to the new transposed object
Implements gko::Transposable.
transpose() [2/2]
template<typename ValueType = default_precision> void gko::matrix::Dense< ValueType >::transpose (Dense< ValueType > * output) const
Writes the transposed matrix into the given output matrix.
Parameters
output The output matrix. It must have the dimensions gko::transpose(this->get_size())
The documentation for this class was generated from the following files:
ginkgo/core/base/mtx_io.hpp
ginkgo/core/matrix/dense.hpp