Ginkgo: gko::matrix::Diagonal< ValueType > Class Template Reference
gko::matrix::Diagonal< ValueType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
This class is a utility which efficiently implements the diagonal matrix (a linear operator which scales a vector row wise).
#include <ginkgo/core/matrix/diagonal.hpp>
Public Types
using value_type = ValueType
using index_type = int64
using mat_data = matrix_data< ValueType, int64 >
using mat_data32 = matrix_data< ValueType, int32 >
using device_mat_data = device_matrix_data< ValueType, int64 >
using device_mat_data32 = device_matrix_data< ValueType, int32 >
using absolute_type = remove_complex< Diagonal >
Public Types inherited from gko::EnablePolymorphicAssignment< Diagonal< ValueType > >
using result_type = Diagonal< ValueType >
Public Types inherited from gko::ConvertibleTo< Diagonal< ValueType > >
using result_type = Diagonal< ValueType >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, int32 > >
using result_type = Csr< ValueType, int32 >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, int64 > >
using result_type = Csr< ValueType, int64 >
Public Types inherited from gko::ConvertibleTo< Diagonal< next_precision< ValueType > > >
using result_type = Diagonal< next_precision< ValueType > >
Public Types inherited from gko::WritableToMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::WritableToMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::ReadableFromMatrixData< ValueType, int32 >
using value_type = ValueType
using index_type = int32
Public Types inherited from gko::ReadableFromMatrixData< ValueType, int64 >
using value_type = ValueType
using index_type = int64
Public Types inherited from gko::EnableAbsoluteComputation< remove_complex< Diagonal< ValueType > > >
using absolute_type = remove_complex< Diagonal< ValueType > >
Public Member Functions
std::unique_ptr< LinOp > transpose () const override
Returns a LinOp representing the transpose of the Transposable object.
std::unique_ptr< LinOp > conj_transpose () const override
Returns a LinOp representing the conjugate transpose of the Transposable object.
void convert_to (Diagonal< next_precision< ValueType >> *result) const override
void move_to (Diagonal< next_precision< ValueType >> *result) override
void convert_to (Csr< ValueType, int32 > *result) const override
void move_to (Csr< ValueType, int32 > *result) override
void convert_to (Csr< ValueType, int64 > *result) const override
void move_to (Csr< ValueType, int64 > *result) override
std::unique_ptr< absolute_type > compute_absolute () const override
Gets the AbsoluteLinOp.
void compute_absolute_inplace () override
Compute absolute inplace on each element.
value_type * get_values () noexcept
Returns a pointer to the array of values of the matrix.
const value_type * get_const_values () const noexcept
Returns a pointer to the array of values of the matrix.
void rapply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
Applies the diagonal matrix from the right side to a matrix b, which means scales the columns of b with the according diagonal entries.
void inverse_apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
Applies the inverse of the diagonal matrix to a matrix b, which means scales the columns of b with the inverse of the according diagonal entries.
void read (const mat_data &data) override
void read (const mat_data32 &data) override
void read (const device_mat_data &data) override
void read (const device_mat_data32 &data) override
void read (device_mat_data &&data) override
void read (device_mat_data32 &&data) override
void write (mat_data &data) const override
void write (mat_data32 &data) const override
Public Member Functions inherited from gko::EnableLinOp< Diagonal< ValueType > >
const Diagonal< ValueType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
Diagonal< ValueType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
const Diagonal< ValueType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
Diagonal< ValueType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< Diagonal< ValueType >, LinOp >
std::unique_ptr< Diagonal< ValueType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Diagonal< ValueType > > create_default () const
std::unique_ptr< Diagonal< ValueType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< Diagonal< ValueType > > clone () const
Diagonal< ValueType > * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, Diagonal< ValueType > > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, Diagonal< ValueType > > * copy_from (const std::unique_ptr< Derived > &other)
Diagonal< ValueType > * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Diagonal< ValueType > * move_from (ptr_param< PolymorphicObject > other)
Diagonal< ValueType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
LinOp & operator= (const LinOp &)=default
Copy-assigns a LinOp.
LinOp & operator= (LinOp &&other)
Move-assigns a LinOp.
LinOp (const LinOp &)=default
Copy-constructs a LinOp.
LinOp (LinOp &&other)
Move-constructs a LinOp.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (const std::unique_ptr< Derived > &other)
LinOp * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
LinOp * move_from (ptr_param< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (std::unique_ptr< Derived, Deleter > &&other)
Moves another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (const std::unique_ptr< Derived, Deleter > &other)
Copies another object into this object.
PolymorphicObject * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Copies another object into this object.
PolymorphicObject * move_from (ptr_param< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
void remove_logger (ptr_param< const Logger > logger)
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::log::Loggable
void remove_logger (ptr_param< const Logger > logger)
Public Member Functions inherited from gko::EnablePolymorphicAssignment< Diagonal< ValueType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< Diagonal< ValueType > >
void convert_to (ptr_param< result_type > result) const
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, int32 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, int64 > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Diagonal< next_precision< ValueType > > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::WritableToMatrixData< ValueType, int32 >
virtual void write (matrix_data< ValueType, int32 > &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::WritableToMatrixData< ValueType, int64 >
virtual void write (matrix_data< ValueType, int64 > &data) const=0
Writes a matrix to a matrix_data structure.
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, int32 >
virtual void read (const matrix_data< ValueType, int32 > &data)=0
Reads a matrix from a matrix_data structure.
void read (const matrix_assembly_data< ValueType, int32 > &data)
Reads a matrix from a matrix_assembly_data structure.
virtual void read (const device_matrix_data< ValueType, int32 > &data)
Reads a matrix from a device_matrix_data structure.
virtual void read (device_matrix_data< ValueType, int32 > &&data)
Reads a matrix from a device_matrix_data structure.
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, int64 >
virtual void read (const matrix_data< ValueType, int64 > &data)=0
Reads a matrix from a matrix_data structure.
void read (const matrix_assembly_data< ValueType, int64 > &data)
Reads a matrix from a matrix_assembly_data structure.
virtual void read (const device_matrix_data< ValueType, int64 > &data)
Reads a matrix from a device_matrix_data structure.
virtual void read (device_matrix_data< ValueType, int64 > &&data)
Reads a matrix from a device_matrix_data structure.
Public Member Functions inherited from gko::EnableAbsoluteComputation< remove_complex< Diagonal< ValueType > > >
std::unique_ptr< LinOp > compute_absolute_linop () const override
Gets the absolute LinOp.
Static Public Member Functions
static std::unique_ptr< const Diagonal > create_const (std::shared_ptr< const Executor > exec, size_type size, gko::detail::const_array_view< ValueType > &&values)
Creates a constant (immutable) Diagonal matrix from a constant array.
Static Public Member Functions inherited from gko::EnableCreateMethod< Diagonal< ValueType > >
static std::unique_ptr< Diagonal< ValueType > > create (Args &&... args)
Friends
class EnablePolymorphicObject< Diagonal, LinOp >
class EnableCreateMethod< Diagonal >
class Csr< ValueType, int32 >
class Csr< ValueType, int64 >
class Diagonal< to_complex< ValueType > >
class Diagonal< next_precision< ValueType > >
Detailed Description
template<typename ValueType = default_precision>
class gko::matrix::Diagonal< ValueType >
This class is a utility which efficiently implements the diagonal matrix (a linear operator which scales a vector row wise).
Objects of the Diagonal class always represent a square matrix, and require one array to store their values.
Template Parameters
ValueType precision of matrix elements
IndexType precision of matrix indexes of a CSR matrix the diagonal is applied or converted to.
Member Function Documentation
compute_absolute()
template<typename ValueType = default_precision> std::unique_ptr<absolute_type> gko::matrix::Diagonal< ValueType >::compute_absolute () const override virtual
Gets the AbsoluteLinOp.
Returns
a pointer to the new absolute object
Implements gko::EnableAbsoluteComputation< remove_complex< Diagonal< ValueType > > >.
conj_transpose()
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Diagonal< ValueType >::conj_transpose () const override virtual
Returns a LinOp representing the conjugate transpose of the Transposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::Transposable.
create_const()
template<typename ValueType = default_precision> static std::unique_ptr<const Diagonal> gko::matrix::Diagonal< ValueType >::create_const (std::shared_ptr< const Executor > exec, size_type size, gko::detail::const_array_view< ValueType > && values) inline static
Creates a constant (immutable) Diagonal matrix from a constant array.
Parameters
exec the executor to create the matrix on
size the size of the square matrix
values the value array of the matrix
Returns
A smart pointer to the constant matrix wrapping the input array (if it resides on the same executor as the matrix) or a copy of the array on the correct executor.
get_const_values()
template<typename ValueType = default_precision> const value_type* gko::matrix::Diagonal< ValueType >::get_const_values () const inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_values()
template<typename ValueType = default_precision> value_type* gko::matrix::Diagonal< ValueType >::get_values () inline noexcept
Returns a pointer to the array of values of the matrix.
Returns
the pointer to the array of values
References gko::array< ValueType >::get_data().
inverse_apply()
template<typename ValueType = default_precision> void gko::matrix::Diagonal< ValueType >::inverse_apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const inline
Applies the inverse of the diagonal matrix to a matrix b, which means scales the columns of b with the inverse of the according diagonal entries.
Parameters
b the input vector(s) on which the inverse of the diagonal matrix is applied
x the output vector(s) where the result is stored
References gko::ptr_param< T >::get().
rapply()
template<typename ValueType = default_precision> void gko::matrix::Diagonal< ValueType >::rapply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const inline
Applies the diagonal matrix from the right side to a matrix b, which means scales the columns of b with the according diagonal entries.
Parameters
b the input vector(s) on which the diagonal matrix is applied
x the output vector(s) where the result is stored
References gko::ptr_param< T >::get().
transpose()
template<typename ValueType = default_precision> std::unique_ptr<LinOp> gko::matrix::Diagonal< ValueType >::transpose () const override virtual
Returns a LinOp representing the transpose of the Transposable object.
Returns
a pointer to the new transposed object
Implements gko::Transposable.
The documentation for this class was generated from the following files:
ginkgo/core/base/lin_op.hpp
ginkgo/core/matrix/diagonal.hpp