Ginkgo: gko::matrix::SparsityCsr< ValueType, IndexType > Class Template Reference
gko::matrix::SparsityCsr< ValueType, IndexType > Class Template Reference
Linear Operators » SpMV employing different Matrix formats | Linear Operators
SparsityCsr is a matrix format which stores only the sparsity pattern of a sparse matrix by compressing each row of the matrix (compressed sparse row format).
#include <ginkgo/core/matrix/sparsity_csr.hpp>
Public Types
using value_type = ValueType
using index_type = IndexType
using transposed_type = SparsityCsr< IndexType, ValueType >
using mat_data = matrix_data< ValueType, IndexType >
using device_mat_data = device_matrix_data< ValueType, IndexType >
Public Types inherited from gko::EnablePolymorphicAssignment< SparsityCsr< ValueType, IndexType > >
using result_type = SparsityCsr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< SparsityCsr< ValueType, IndexType > >
using result_type = SparsityCsr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
using result_type = Csr< ValueType, IndexType >
Public Types inherited from gko::ConvertibleTo< Dense< ValueType > >
using result_type = Dense< ValueType >
Public Types inherited from gko::ReadableFromMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Types inherited from gko::WritableToMatrixData< ValueType, IndexType >
using value_type = ValueType
using index_type = IndexType
Public Member Functions
void convert_to (Csr< ValueType, IndexType > *result) const override
void move_to (Csr< ValueType, IndexType > *result) override
void convert_to (Dense< ValueType > *result) const override
void move_to (Dense< ValueType > *result) override
void read (const mat_data &data) override
Reads a matrix from a matrix_data structure.
void read (const device_mat_data &data) override
Reads a matrix from a device_matrix_data structure.
void read (device_mat_data &&data) override
Reads a matrix from a device_matrix_data structure.
void write (mat_data &data) const override
Writes a matrix to a matrix_data structure.
std::unique_ptr< LinOp > transpose () const override
Returns a LinOp representing the transpose of the Transposable object.
std::unique_ptr< LinOp > conj_transpose () const override
Returns a LinOp representing the conjugate transpose of the Transposable object.
std::unique_ptr< SparsityCsr > to_adjacency_matrix () const
Transforms the sparsity matrix to an adjacency matrix.
void sort_by_column_index ()
Sorts each row by column index.
bool is_sorted_by_column_index () const
index_type * get_col_idxs () noexcept
Returns the column indices of the matrix.
const index_type * get_const_col_idxs () const noexcept
Returns the column indices of the matrix.
index_type * get_row_ptrs () noexcept
Returns the row pointers of the matrix.
const index_type * get_const_row_ptrs () const noexcept
Returns the row pointers of the matrix.
value_type * get_value () noexcept
Returns the value stored in the matrix.
const value_type * get_const_value () const noexcept
Returns the value stored in the matrix.
size_type get_num_nonzeros () const noexcept
Returns the number of elements explicitly stored in the matrix.
SparsityCsr & operator= (const SparsityCsr &)
Copy-assigns a SparsityCsr matrix.
SparsityCsr & operator= (SparsityCsr &&)
Move-assigns a SparsityCsr matrix.
SparsityCsr (const SparsityCsr &)
Copy-constructs a SparsityCsr matrix.
SparsityCsr (SparsityCsr &&)
Move-constructs a SparsityCsr matrix.
Public Member Functions inherited from gko::EnableLinOp< SparsityCsr< ValueType, IndexType > >
const SparsityCsr< ValueType, IndexType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
SparsityCsr< ValueType, IndexType > * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
const SparsityCsr< ValueType, IndexType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
SparsityCsr< ValueType, IndexType > * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< SparsityCsr< ValueType, IndexType >, LinOp >
std::unique_ptr< SparsityCsr< ValueType, IndexType > > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > create_default () const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< SparsityCsr< ValueType, IndexType > > clone () const
SparsityCsr< ValueType, IndexType > * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, SparsityCsr< ValueType, IndexType > > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, SparsityCsr< ValueType, IndexType > > * copy_from (const std::unique_ptr< Derived > &other)
SparsityCsr< ValueType, IndexType > * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
SparsityCsr< ValueType, IndexType > * move_from (ptr_param< PolymorphicObject > other)
SparsityCsr< ValueType, IndexType > * clear ()
Public Member Functions inherited from gko::LinOp
LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x)
Applies a linear operator to a vector (or a sequence of vectors).
const LinOp * apply (ptr_param< const LinOp > b, ptr_param< LinOp > x) const
LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x)
Performs the operation x = alpha * op(b) + beta * x.
const LinOp * apply (ptr_param< const LinOp > alpha, ptr_param< const LinOp > b, ptr_param< const LinOp > beta, ptr_param< LinOp > x) const
const dim< 2 > & get_size () const noexcept
Returns the size of the operator.
virtual bool apply_uses_initial_guess () const
Returns true if the linear operator uses the data given in x as an initial guess.
LinOp & operator= (const LinOp &)=default
Copy-assigns a LinOp.
LinOp & operator= (LinOp &&other)
Move-assigns a LinOp.
LinOp (const LinOp &)=default
Copy-constructs a LinOp.
LinOp (LinOp &&other)
Move-constructs a LinOp.
Public Member Functions inherited from gko::EnableAbstractPolymorphicObject< LinOp >
std::unique_ptr< LinOp > create_default (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > create_default () const
std::unique_ptr< LinOp > clone (std::shared_ptr< const Executor > exec) const
std::unique_ptr< LinOp > clone () const
LinOp * copy_from (const PolymorphicObject *other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (std::unique_ptr< Derived > &&other)
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, LinOp > * copy_from (const std::unique_ptr< Derived > &other)
LinOp * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
LinOp * move_from (ptr_param< PolymorphicObject > other)
LinOp * clear ()
Public Member Functions inherited from gko::PolymorphicObject
PolymorphicObject & operator= (const PolymorphicObject &)
std::unique_ptr< PolymorphicObject > create_default (std::shared_ptr< const Executor > exec) const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > create_default () const
Creates a new "default" object of the same dynamic type as this object.
std::unique_ptr< PolymorphicObject > clone (std::shared_ptr< const Executor > exec) const
Creates a clone of the object.
std::unique_ptr< PolymorphicObject > clone () const
Creates a clone of the object.
PolymorphicObject * copy_from (const PolymorphicObject *other)
Copies another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (std::unique_ptr< Derived, Deleter > &&other)
Moves another object into this object.
template<typename Derived , typename Deleter >
std::enable_if_t< std::is_base_of< PolymorphicObject, std::decay_t< Derived > >::value, PolymorphicObject > * copy_from (const std::unique_ptr< Derived, Deleter > &other)
Copies another object into this object.
PolymorphicObject * copy_from (const std::shared_ptr< const PolymorphicObject > &other)
Copies another object into this object.
PolymorphicObject * move_from (ptr_param< PolymorphicObject > other)
Moves another object into this object.
PolymorphicObject * clear ()
Transforms the object into its default state.
std::shared_ptr< const Executor > get_executor () const noexcept
Returns the Executor of the object.
Public Member Functions inherited from gko::log::EnableLogging< PolymorphicObject >
void add_logger (std::shared_ptr< const Logger > logger) override
void remove_logger (const Logger *logger) override
void remove_logger (ptr_param< const Logger > logger)
const std::vector< std::shared_ptr< const Logger > > & get_loggers () const override
void clear_loggers () override
Public Member Functions inherited from gko::log::Loggable
void remove_logger (ptr_param< const Logger > logger)
Public Member Functions inherited from gko::EnablePolymorphicAssignment< SparsityCsr< ValueType, IndexType > >
void convert_to (result_type *result) const override
Converts the implementer to an object of type result_type.
void move_to (result_type *result) override
Converts the implementer to an object of type result_type by moving data from this object.
Public Member Functions inherited from gko::ConvertibleTo< SparsityCsr< ValueType, IndexType > >
void convert_to (ptr_param< result_type > result) const
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Csr< ValueType, IndexType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ConvertibleTo< Dense< ValueType > >
virtual void convert_to (result_type *result) const=0
Converts the implementer to an object of type result_type.
void convert_to (ptr_param< result_type > result) const
virtual void move_to (result_type *result)=0
Converts the implementer to an object of type result_type by moving data from this object.
void move_to (ptr_param< result_type > result)
Public Member Functions inherited from gko::ReadableFromMatrixData< ValueType, IndexType >
void read (const matrix_assembly_data< ValueType, IndexType > &data)
Reads a matrix from a matrix_assembly_data structure.
Static Public Member Functions
static std::unique_ptr< const SparsityCsr > create_const (std::shared_ptr< const Executor > exec, const dim< 2 > &size, gko::detail::const_array_view< IndexType > &&col_idxs, gko::detail::const_array_view< IndexType > &&row_ptrs, ValueType value=one< ValueType >())
Creates a constant (immutable) SparsityCsr matrix from constant arrays.
Static Public Member Functions inherited from gko::EnableCreateMethod< SparsityCsr< ValueType, IndexType > >
static std::unique_ptr< SparsityCsr< ValueType, IndexType > > create (Args &&... args)
Friends
class EnableCreateMethod< SparsityCsr >
class EnablePolymorphicObject< SparsityCsr, LinOp >
class Csr< ValueType, IndexType >
class Dense< ValueType >
class Fbcsr< ValueType, IndexType >
Detailed Description
template<typename ValueType = default_precision, typename IndexType = int32>
class gko::matrix::SparsityCsr< ValueType, IndexType >
SparsityCsr is a matrix format which stores only the sparsity pattern of a sparse matrix by compressing each row of the matrix (compressed sparse row format).
The values of the nonzero elements are stored as a value array of length 1. All the values in the matrix are equal to this value. By default, this value is set to 1.0. A row pointer array also stores the linearized starting index of each row. An additional column index array is used to identify the column where a nonzero is present.
Template Parameters
ValueType precision of vectors in apply
IndexType precision of matrix indexes
Constructor & Destructor Documentation
SparsityCsr() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::SparsityCsr< ValueType, IndexType >::SparsityCsr (const SparsityCsr< ValueType, IndexType > &)
Copy-constructs a SparsityCsr matrix.
Inherits executor, strategy and data.
SparsityCsr() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> gko::matrix::SparsityCsr< ValueType, IndexType >::SparsityCsr (SparsityCsr< ValueType, IndexType > &&)
Move-constructs a SparsityCsr matrix.
Inherits executor, moves the data and leaves the moved-from object in an empty state (0x0 LinOp with unchanged executor, no nonzeros and valid row pointers).
Member Function Documentation
conj_transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<LinOp> gko::matrix::SparsityCsr< ValueType, IndexType >::conj_transpose () const override virtual
Returns a LinOp representing the conjugate transpose of the Transposable object.
Returns
a pointer to the new conjugate transposed object
Implements gko::Transposable.
create_const()
template<typename ValueType = default_precision, typename IndexType = int32> static std::unique_ptr<const SparsityCsr> gko::matrix::SparsityCsr< ValueType, IndexType >::create_const (std::shared_ptr< const Executor > exec, const dim< 2 > & size, gko::detail::const_array_view< IndexType > && col_idxs, gko::detail::const_array_view< IndexType > && row_ptrs, ValueType value = one<ValueType>()) inline static
Creates a constant (immutable) SparsityCsr matrix from constant arrays.
Parameters
exec the executor to create the matrix on
size the dimensions of the matrix
values the value array of the matrix
col_idxs the column index array of the matrix
row_ptrs the row pointer array of the matrix
strategy the strategy the matrix uses for SpMV operations
Returns
A smart pointer to the constant matrix wrapping the input arrays (if they reside on the same executor as the matrix) or a copy of these arrays on the correct executor.
get_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_col_idxs () inline noexcept
Returns the column indices of the matrix.
Returns
the column indices of the matrix.
References gko::array< ValueType >::get_data().
get_const_col_idxs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_col_idxs () const inline noexcept
Returns the column indices of the matrix.
Returns
the column indices of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_const_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> const index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_row_ptrs () const inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_const_value()
template<typename ValueType = default_precision, typename IndexType = int32> const value_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_const_value () const inline noexcept
Returns the value stored in the matrix.
Returns
the value of the matrix.
Note
This is the constant version of the function, which can be significantly more memory efficient than the non-constant version, so always prefer this version.
References gko::array< ValueType >::get_const_data().
get_num_nonzeros()
template<typename ValueType = default_precision, typename IndexType = int32> size_type gko::matrix::SparsityCsr< ValueType, IndexType >::get_num_nonzeros () const inline noexcept
Returns the number of elements explicitly stored in the matrix.
Returns
the number of elements explicitly stored in the matrix
References gko::array< ValueType >::get_num_elems().
get_row_ptrs()
template<typename ValueType = default_precision, typename IndexType = int32> index_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_row_ptrs () inline noexcept
Returns the row pointers of the matrix.
Returns
the row pointers of the matrix.
References gko::array< ValueType >::get_data().
get_value()
template<typename ValueType = default_precision, typename IndexType = int32> value_type* gko::matrix::SparsityCsr< ValueType, IndexType >::get_value () inline noexcept
Returns the value stored in the matrix.
Returns
the value of the matrix.
References gko::array< ValueType >::get_data().
operator=() [1/2]
template<typename ValueType = default_precision, typename IndexType = int32> SparsityCsr& gko::matrix::SparsityCsr< ValueType, IndexType >::operator= (const SparsityCsr< ValueType, IndexType > &)
Copy-assigns a SparsityCsr matrix.
Preserves executor, copies everything else.
operator=() [2/2]
template<typename ValueType = default_precision, typename IndexType = int32> SparsityCsr& gko::matrix::SparsityCsr< ValueType, IndexType >::operator= (SparsityCsr< ValueType, IndexType > &&)
Move-assigns a SparsityCsr matrix.
Preserves executor, moves the data and leaves the moved-from object in an empty state (0x0 LinOp with unchanged executor, no nonzeros and valid row pointers).
read() [1/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::read (const device_mat_data & data) override virtual
Reads a matrix from a device_matrix_data structure.
Parameters
data the device_matrix_data structure.
Reimplemented from gko::ReadableFromMatrixData< ValueType, IndexType >.
read() [2/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::read (const mat_data & data) override virtual
Reads a matrix from a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::ReadableFromMatrixData< ValueType, IndexType >.
read() [3/3]
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::read (device_mat_data && data) override virtual
Reads a matrix from a device_matrix_data structure.
The structure may be emptied by this function.
Parameters
data the device_matrix_data structure.
Reimplemented from gko::ReadableFromMatrixData< ValueType, IndexType >.
to_adjacency_matrix()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<SparsityCsr> gko::matrix::SparsityCsr< ValueType, IndexType >::to_adjacency_matrix () const
Transforms the sparsity matrix to an adjacency matrix.
As the adjacency matrix has to be square, the input SparsityCsr matrix for this function to work has to be square.
Note
The adjacency matrix in this case is the sparsity pattern but with the diagonal ones removed. This is mainly used for the reordering/partitioning as taken in by graph libraries such as METIS.
transpose()
template<typename ValueType = default_precision, typename IndexType = int32> std::unique_ptr<LinOp> gko::matrix::SparsityCsr< ValueType, IndexType >::transpose () const override virtual
Returns a LinOp representing the transpose of the Transposable object.
Returns
a pointer to the new transposed object
Implements gko::Transposable.
write()
template<typename ValueType = default_precision, typename IndexType = int32> void gko::matrix::SparsityCsr< ValueType, IndexType >::write (mat_data & data) const override virtual
Writes a matrix to a matrix_data structure.
Parameters
data the matrix_data structure
Implements gko::WritableToMatrixData< ValueType, IndexType >.
The documentation for this class was generated from the following files:
ginkgo/core/matrix/csr.hpp
ginkgo/core/matrix/sparsity_csr.hpp